// Code generated by protoc-gen-go. DO NOT EDIT.
// source: random_number.proto

package messages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RandomNumberResponse struct {
	Number               []byte   `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RandomNumberResponse) Reset()         { *m = RandomNumberResponse{} }
func (m *RandomNumberResponse) String() string { return proto.CompactTextString(m) }
func (*RandomNumberResponse) ProtoMessage()    {}
func (*RandomNumberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_522c02bfcae4ed2a, []int{0}
}

func (m *RandomNumberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RandomNumberResponse.Unmarshal(m, b)
}
func (m *RandomNumberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RandomNumberResponse.Marshal(b, m, deterministic)
}
func (m *RandomNumberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RandomNumberResponse.Merge(m, src)
}
func (m *RandomNumberResponse) XXX_Size() int {
	return xxx_messageInfo_RandomNumberResponse.Size(m)
}
func (m *RandomNumberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RandomNumberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RandomNumberResponse proto.InternalMessageInfo

func (m *RandomNumberResponse) GetNumber() []byte {
	if m != nil {
		return m.Number
	}
	return nil
}

type RandomNumberRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RandomNumberRequest) Reset()         { *m = RandomNumberRequest{} }
func (m *RandomNumberRequest) String() string { return proto.CompactTextString(m) }
func (*RandomNumberRequest) ProtoMessage()    {}
func (*RandomNumberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_522c02bfcae4ed2a, []int{1}
}

func (m *RandomNumberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RandomNumberRequest.Unmarshal(m, b)
}
func (m *RandomNumberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RandomNumberRequest.Marshal(b, m, deterministic)
}
func (m *RandomNumberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RandomNumberRequest.Merge(m, src)
}
func (m *RandomNumberRequest) XXX_Size() int {
	return xxx_messageInfo_RandomNumberRequest.Size(m)
}
func (m *RandomNumberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RandomNumberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RandomNumberRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RandomNumberResponse)(nil), "RandomNumberResponse")
	proto.RegisterType((*RandomNumberRequest)(nil), "RandomNumberRequest")
}

func init() { proto.RegisterFile("random_number.proto", fileDescriptor_522c02bfcae4ed2a) }

var fileDescriptor_522c02bfcae4ed2a = []byte{
	// 94 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x4a, 0xcc, 0x4b,
	0xc9, 0xcf, 0x8d, 0xcf, 0x2b, 0xcd, 0x4d, 0x4a, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57,
	0xd2, 0xe3, 0x12, 0x09, 0x02, 0x0b, 0xfb, 0x81, 0x45, 0x83, 0x52, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a,
	0x53, 0x85, 0xc4, 0xb8, 0xd8, 0x20, 0xea, 0x24, 0x18, 0x15, 0x18, 0x35, 0x78, 0x82, 0xa0, 0x3c,
	0x25, 0x51, 0x2e, 0x61, 0x54, 0xf5, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x49, 0x6c, 0x60, 0xd3, 0x8c,
	0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7f, 0x2e, 0x38, 0x84, 0x64, 0x00, 0x00, 0x00,
}
