// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages/hww.proto

/*
Package messages is a generated protocol buffer package.

It is generated from these files:
	messages/hww.proto

It has these top-level messages:
	Error
	Success
	RandomNumberResponse
	RandomNumberRequest
	DeviceInfoRequest
	DeviceInfoResponse
	SetDeviceNameRequest
	SetDeviceLanguageRequest
	SetPasswordRequest
	CreateBackupRequest
	ShowMnemonicRequest
	BTCPubRequest
	PubResponse
	Request
	Response
*/
package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BTCCoin int32

const (
	BTCCoin_BTC  BTCCoin = 0
	BTCCoin_TBTC BTCCoin = 1
	BTCCoin_LTC  BTCCoin = 2
	BTCCoin_TLTC BTCCoin = 3
)

var BTCCoin_name = map[int32]string{
	0: "BTC",
	1: "TBTC",
	2: "LTC",
	3: "TLTC",
}
var BTCCoin_value = map[string]int32{
	"BTC":  0,
	"TBTC": 1,
	"LTC":  2,
	"TLTC": 3,
}

func (x BTCCoin) String() string {
	return proto.EnumName(BTCCoin_name, int32(x))
}
func (BTCCoin) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type BTCScriptType int32

const (
	BTCScriptType_SCRIPT_UNKNOWN     BTCScriptType = 0
	BTCScriptType_SCRIPT_P2PKH       BTCScriptType = 1
	BTCScriptType_SCRIPT_P2WPKH_P2SH BTCScriptType = 2
	BTCScriptType_SCRIPT_P2WPKH      BTCScriptType = 3
)

var BTCScriptType_name = map[int32]string{
	0: "SCRIPT_UNKNOWN",
	1: "SCRIPT_P2PKH",
	2: "SCRIPT_P2WPKH_P2SH",
	3: "SCRIPT_P2WPKH",
}
var BTCScriptType_value = map[string]int32{
	"SCRIPT_UNKNOWN":     0,
	"SCRIPT_P2PKH":       1,
	"SCRIPT_P2WPKH_P2SH": 2,
	"SCRIPT_P2WPKH":      3,
}

func (x BTCScriptType) String() string {
	return proto.EnumName(BTCScriptType_name, int32(x))
}
func (BTCScriptType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type BTCOutputType int32

const (
	BTCOutputType_UNKNOWN BTCOutputType = 0
	BTCOutputType_P2PKH   BTCOutputType = 1
	BTCOutputType_P2SH    BTCOutputType = 2
	BTCOutputType_P2WPKH  BTCOutputType = 3
	BTCOutputType_P2WSH   BTCOutputType = 4
)

var BTCOutputType_name = map[int32]string{
	0: "UNKNOWN",
	1: "P2PKH",
	2: "P2SH",
	3: "P2WPKH",
	4: "P2WSH",
}
var BTCOutputType_value = map[string]int32{
	"UNKNOWN": 0,
	"P2PKH":   1,
	"P2SH":    2,
	"P2WPKH":  3,
	"P2WSH":   4,
}

func (x BTCOutputType) String() string {
	return proto.EnumName(BTCOutputType_name, int32(x))
}
func (BTCOutputType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type BTCPubRequest_OutputType int32

const (
	BTCPubRequest_TPUB    BTCPubRequest_OutputType = 0
	BTCPubRequest_XPUB    BTCPubRequest_OutputType = 1
	BTCPubRequest_YPUB    BTCPubRequest_OutputType = 2
	BTCPubRequest_ZPUB    BTCPubRequest_OutputType = 3
	BTCPubRequest_ADDRESS BTCPubRequest_OutputType = 4
)

var BTCPubRequest_OutputType_name = map[int32]string{
	0: "TPUB",
	1: "XPUB",
	2: "YPUB",
	3: "ZPUB",
	4: "ADDRESS",
}
var BTCPubRequest_OutputType_value = map[string]int32{
	"TPUB":    0,
	"XPUB":    1,
	"YPUB":    2,
	"ZPUB":    3,
	"ADDRESS": 4,
}

func (x BTCPubRequest_OutputType) String() string {
	return proto.EnumName(BTCPubRequest_OutputType_name, int32(x))
}
func (BTCPubRequest_OutputType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{11, 0} }

type Error struct {
	Code    int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Success struct {
}

func (m *Success) Reset()                    { *m = Success{} }
func (m *Success) String() string            { return proto.CompactTextString(m) }
func (*Success) ProtoMessage()               {}
func (*Success) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type RandomNumberResponse struct {
	Number []byte `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (m *RandomNumberResponse) Reset()                    { *m = RandomNumberResponse{} }
func (m *RandomNumberResponse) String() string            { return proto.CompactTextString(m) }
func (*RandomNumberResponse) ProtoMessage()               {}
func (*RandomNumberResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RandomNumberResponse) GetNumber() []byte {
	if m != nil {
		return m.Number
	}
	return nil
}

type RandomNumberRequest struct {
}

func (m *RandomNumberRequest) Reset()                    { *m = RandomNumberRequest{} }
func (m *RandomNumberRequest) String() string            { return proto.CompactTextString(m) }
func (*RandomNumberRequest) ProtoMessage()               {}
func (*RandomNumberRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type DeviceInfoRequest struct {
}

func (m *DeviceInfoRequest) Reset()                    { *m = DeviceInfoRequest{} }
func (m *DeviceInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*DeviceInfoRequest) ProtoMessage()               {}
func (*DeviceInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type DeviceInfoResponse struct {
	Name        string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Initialized bool   `protobuf:"varint,2,opt,name=initialized" json:"initialized,omitempty"`
	Version     string `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
}

func (m *DeviceInfoResponse) Reset()                    { *m = DeviceInfoResponse{} }
func (m *DeviceInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*DeviceInfoResponse) ProtoMessage()               {}
func (*DeviceInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DeviceInfoResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeviceInfoResponse) GetInitialized() bool {
	if m != nil {
		return m.Initialized
	}
	return false
}

func (m *DeviceInfoResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type SetDeviceNameRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *SetDeviceNameRequest) Reset()                    { *m = SetDeviceNameRequest{} }
func (m *SetDeviceNameRequest) String() string            { return proto.CompactTextString(m) }
func (*SetDeviceNameRequest) ProtoMessage()               {}
func (*SetDeviceNameRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SetDeviceNameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SetDeviceLanguageRequest struct {
	Language string `protobuf:"bytes,1,opt,name=language" json:"language,omitempty"`
}

func (m *SetDeviceLanguageRequest) Reset()                    { *m = SetDeviceLanguageRequest{} }
func (m *SetDeviceLanguageRequest) String() string            { return proto.CompactTextString(m) }
func (*SetDeviceLanguageRequest) ProtoMessage()               {}
func (*SetDeviceLanguageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SetDeviceLanguageRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

type SetPasswordRequest struct {
}

func (m *SetPasswordRequest) Reset()                    { *m = SetPasswordRequest{} }
func (m *SetPasswordRequest) String() string            { return proto.CompactTextString(m) }
func (*SetPasswordRequest) ProtoMessage()               {}
func (*SetPasswordRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type CreateBackupRequest struct {
	// TODO add backup creation args
	Timestamp      uint32 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	TimezoneOffset int32  `protobuf:"varint,2,opt,name=timezone_offset,json=timezoneOffset" json:"timezone_offset,omitempty"`
}

func (m *CreateBackupRequest) Reset()                    { *m = CreateBackupRequest{} }
func (m *CreateBackupRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateBackupRequest) ProtoMessage()               {}
func (*CreateBackupRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *CreateBackupRequest) GetTimestamp() uint32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *CreateBackupRequest) GetTimezoneOffset() int32 {
	if m != nil {
		return m.TimezoneOffset
	}
	return 0
}

type ShowMnemonicRequest struct {
}

func (m *ShowMnemonicRequest) Reset()                    { *m = ShowMnemonicRequest{} }
func (m *ShowMnemonicRequest) String() string            { return proto.CompactTextString(m) }
func (*ShowMnemonicRequest) ProtoMessage()               {}
func (*ShowMnemonicRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type BTCPubRequest struct {
	Keypath    []uint32                 `protobuf:"varint,1,rep,packed,name=keypath" json:"keypath,omitempty"`
	ScriptType BTCScriptType            `protobuf:"varint,2,opt,name=script_type,json=scriptType,enum=BTCScriptType" json:"script_type,omitempty"`
	Coin       BTCCoin                  `protobuf:"varint,3,opt,name=coin,enum=BTCCoin" json:"coin,omitempty"`
	OutputType BTCPubRequest_OutputType `protobuf:"varint,4,opt,name=output_type,json=outputType,enum=BTCPubRequest_OutputType" json:"output_type,omitempty"`
	Display    bool                     `protobuf:"varint,5,opt,name=display" json:"display,omitempty"`
}

func (m *BTCPubRequest) Reset()                    { *m = BTCPubRequest{} }
func (m *BTCPubRequest) String() string            { return proto.CompactTextString(m) }
func (*BTCPubRequest) ProtoMessage()               {}
func (*BTCPubRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *BTCPubRequest) GetKeypath() []uint32 {
	if m != nil {
		return m.Keypath
	}
	return nil
}

func (m *BTCPubRequest) GetScriptType() BTCScriptType {
	if m != nil {
		return m.ScriptType
	}
	return BTCScriptType_SCRIPT_UNKNOWN
}

func (m *BTCPubRequest) GetCoin() BTCCoin {
	if m != nil {
		return m.Coin
	}
	return BTCCoin_BTC
}

func (m *BTCPubRequest) GetOutputType() BTCPubRequest_OutputType {
	if m != nil {
		return m.OutputType
	}
	return BTCPubRequest_TPUB
}

func (m *BTCPubRequest) GetDisplay() bool {
	if m != nil {
		return m.Display
	}
	return false
}

type PubResponse struct {
	Pub string `protobuf:"bytes,1,opt,name=pub" json:"pub,omitempty"`
}

func (m *PubResponse) Reset()                    { *m = PubResponse{} }
func (m *PubResponse) String() string            { return proto.CompactTextString(m) }
func (*PubResponse) ProtoMessage()               {}
func (*PubResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *PubResponse) GetPub() string {
	if m != nil {
		return m.Pub
	}
	return ""
}

type Request struct {
	// Types that are valid to be assigned to Request:
	//	*Request_RandomNumber
	//	*Request_DeviceName
	//	*Request_DeviceLanguage
	//	*Request_DeviceInfo
	//	*Request_SetPassword
	//	*Request_CreateBackup
	//	*Request_ShowMnemonic
	//	*Request_BtcPub
	Request isRequest_Request `protobuf_oneof:"request"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type isRequest_Request interface{ isRequest_Request() }

type Request_RandomNumber struct {
	RandomNumber *RandomNumberRequest `protobuf:"bytes,1,opt,name=random_number,json=randomNumber,oneof"`
}
type Request_DeviceName struct {
	DeviceName *SetDeviceNameRequest `protobuf:"bytes,2,opt,name=device_name,json=deviceName,oneof"`
}
type Request_DeviceLanguage struct {
	DeviceLanguage *SetDeviceLanguageRequest `protobuf:"bytes,3,opt,name=device_language,json=deviceLanguage,oneof"`
}
type Request_DeviceInfo struct {
	DeviceInfo *DeviceInfoRequest `protobuf:"bytes,4,opt,name=device_info,json=deviceInfo,oneof"`
}
type Request_SetPassword struct {
	SetPassword *SetPasswordRequest `protobuf:"bytes,5,opt,name=set_password,json=setPassword,oneof"`
}
type Request_CreateBackup struct {
	CreateBackup *CreateBackupRequest `protobuf:"bytes,6,opt,name=create_backup,json=createBackup,oneof"`
}
type Request_ShowMnemonic struct {
	ShowMnemonic *ShowMnemonicRequest `protobuf:"bytes,7,opt,name=show_mnemonic,json=showMnemonic,oneof"`
}
type Request_BtcPub struct {
	BtcPub *BTCPubRequest `protobuf:"bytes,8,opt,name=btc_pub,json=btcPub,oneof"`
}

func (*Request_RandomNumber) isRequest_Request()   {}
func (*Request_DeviceName) isRequest_Request()     {}
func (*Request_DeviceLanguage) isRequest_Request() {}
func (*Request_DeviceInfo) isRequest_Request()     {}
func (*Request_SetPassword) isRequest_Request()    {}
func (*Request_CreateBackup) isRequest_Request()   {}
func (*Request_ShowMnemonic) isRequest_Request()   {}
func (*Request_BtcPub) isRequest_Request()         {}

func (m *Request) GetRequest() isRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *Request) GetRandomNumber() *RandomNumberRequest {
	if x, ok := m.GetRequest().(*Request_RandomNumber); ok {
		return x.RandomNumber
	}
	return nil
}

func (m *Request) GetDeviceName() *SetDeviceNameRequest {
	if x, ok := m.GetRequest().(*Request_DeviceName); ok {
		return x.DeviceName
	}
	return nil
}

func (m *Request) GetDeviceLanguage() *SetDeviceLanguageRequest {
	if x, ok := m.GetRequest().(*Request_DeviceLanguage); ok {
		return x.DeviceLanguage
	}
	return nil
}

func (m *Request) GetDeviceInfo() *DeviceInfoRequest {
	if x, ok := m.GetRequest().(*Request_DeviceInfo); ok {
		return x.DeviceInfo
	}
	return nil
}

func (m *Request) GetSetPassword() *SetPasswordRequest {
	if x, ok := m.GetRequest().(*Request_SetPassword); ok {
		return x.SetPassword
	}
	return nil
}

func (m *Request) GetCreateBackup() *CreateBackupRequest {
	if x, ok := m.GetRequest().(*Request_CreateBackup); ok {
		return x.CreateBackup
	}
	return nil
}

func (m *Request) GetShowMnemonic() *ShowMnemonicRequest {
	if x, ok := m.GetRequest().(*Request_ShowMnemonic); ok {
		return x.ShowMnemonic
	}
	return nil
}

func (m *Request) GetBtcPub() *BTCPubRequest {
	if x, ok := m.GetRequest().(*Request_BtcPub); ok {
		return x.BtcPub
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Request) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Request_OneofMarshaler, _Request_OneofUnmarshaler, _Request_OneofSizer, []interface{}{
		(*Request_RandomNumber)(nil),
		(*Request_DeviceName)(nil),
		(*Request_DeviceLanguage)(nil),
		(*Request_DeviceInfo)(nil),
		(*Request_SetPassword)(nil),
		(*Request_CreateBackup)(nil),
		(*Request_ShowMnemonic)(nil),
		(*Request_BtcPub)(nil),
	}
}

func _Request_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Request)
	// request
	switch x := m.Request.(type) {
	case *Request_RandomNumber:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RandomNumber); err != nil {
			return err
		}
	case *Request_DeviceName:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DeviceName); err != nil {
			return err
		}
	case *Request_DeviceLanguage:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DeviceLanguage); err != nil {
			return err
		}
	case *Request_DeviceInfo:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DeviceInfo); err != nil {
			return err
		}
	case *Request_SetPassword:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SetPassword); err != nil {
			return err
		}
	case *Request_CreateBackup:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CreateBackup); err != nil {
			return err
		}
	case *Request_ShowMnemonic:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ShowMnemonic); err != nil {
			return err
		}
	case *Request_BtcPub:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BtcPub); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Request.Request has unexpected type %T", x)
	}
	return nil
}

func _Request_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Request)
	switch tag {
	case 1: // request.random_number
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RandomNumberRequest)
		err := b.DecodeMessage(msg)
		m.Request = &Request_RandomNumber{msg}
		return true, err
	case 2: // request.device_name
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SetDeviceNameRequest)
		err := b.DecodeMessage(msg)
		m.Request = &Request_DeviceName{msg}
		return true, err
	case 3: // request.device_language
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SetDeviceLanguageRequest)
		err := b.DecodeMessage(msg)
		m.Request = &Request_DeviceLanguage{msg}
		return true, err
	case 4: // request.device_info
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DeviceInfoRequest)
		err := b.DecodeMessage(msg)
		m.Request = &Request_DeviceInfo{msg}
		return true, err
	case 5: // request.set_password
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SetPasswordRequest)
		err := b.DecodeMessage(msg)
		m.Request = &Request_SetPassword{msg}
		return true, err
	case 6: // request.create_backup
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CreateBackupRequest)
		err := b.DecodeMessage(msg)
		m.Request = &Request_CreateBackup{msg}
		return true, err
	case 7: // request.show_mnemonic
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ShowMnemonicRequest)
		err := b.DecodeMessage(msg)
		m.Request = &Request_ShowMnemonic{msg}
		return true, err
	case 8: // request.btc_pub
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BTCPubRequest)
		err := b.DecodeMessage(msg)
		m.Request = &Request_BtcPub{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Request_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Request)
	// request
	switch x := m.Request.(type) {
	case *Request_RandomNumber:
		s := proto.Size(x.RandomNumber)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_DeviceName:
		s := proto.Size(x.DeviceName)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_DeviceLanguage:
		s := proto.Size(x.DeviceLanguage)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_DeviceInfo:
		s := proto.Size(x.DeviceInfo)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_SetPassword:
		s := proto.Size(x.SetPassword)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_CreateBackup:
		s := proto.Size(x.CreateBackup)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_ShowMnemonic:
		s := proto.Size(x.ShowMnemonic)
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_BtcPub:
		s := proto.Size(x.BtcPub)
		n += proto.SizeVarint(8<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Response struct {
	// Types that are valid to be assigned to Response:
	//	*Response_Success
	//	*Response_Error
	//	*Response_RandomNumber
	//	*Response_DeviceInfo
	//	*Response_Pub
	Response isResponse_Response `protobuf_oneof:"response"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type isResponse_Response interface{ isResponse_Response() }

type Response_Success struct {
	Success *Success `protobuf:"bytes,1,opt,name=success,oneof"`
}
type Response_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,oneof"`
}
type Response_RandomNumber struct {
	RandomNumber *RandomNumberResponse `protobuf:"bytes,3,opt,name=random_number,json=randomNumber,oneof"`
}
type Response_DeviceInfo struct {
	DeviceInfo *DeviceInfoResponse `protobuf:"bytes,4,opt,name=device_info,json=deviceInfo,oneof"`
}
type Response_Pub struct {
	Pub *PubResponse `protobuf:"bytes,5,opt,name=pub,oneof"`
}

func (*Response_Success) isResponse_Response()      {}
func (*Response_Error) isResponse_Response()        {}
func (*Response_RandomNumber) isResponse_Response() {}
func (*Response_DeviceInfo) isResponse_Response()   {}
func (*Response_Pub) isResponse_Response()          {}

func (m *Response) GetResponse() isResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *Response) GetSuccess() *Success {
	if x, ok := m.GetResponse().(*Response_Success); ok {
		return x.Success
	}
	return nil
}

func (m *Response) GetError() *Error {
	if x, ok := m.GetResponse().(*Response_Error); ok {
		return x.Error
	}
	return nil
}

func (m *Response) GetRandomNumber() *RandomNumberResponse {
	if x, ok := m.GetResponse().(*Response_RandomNumber); ok {
		return x.RandomNumber
	}
	return nil
}

func (m *Response) GetDeviceInfo() *DeviceInfoResponse {
	if x, ok := m.GetResponse().(*Response_DeviceInfo); ok {
		return x.DeviceInfo
	}
	return nil
}

func (m *Response) GetPub() *PubResponse {
	if x, ok := m.GetResponse().(*Response_Pub); ok {
		return x.Pub
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Response) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Response_OneofMarshaler, _Response_OneofUnmarshaler, _Response_OneofSizer, []interface{}{
		(*Response_Success)(nil),
		(*Response_Error)(nil),
		(*Response_RandomNumber)(nil),
		(*Response_DeviceInfo)(nil),
		(*Response_Pub)(nil),
	}
}

func _Response_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Response)
	// response
	switch x := m.Response.(type) {
	case *Response_Success:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Success); err != nil {
			return err
		}
	case *Response_Error:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Error); err != nil {
			return err
		}
	case *Response_RandomNumber:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RandomNumber); err != nil {
			return err
		}
	case *Response_DeviceInfo:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DeviceInfo); err != nil {
			return err
		}
	case *Response_Pub:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Pub); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Response.Response has unexpected type %T", x)
	}
	return nil
}

func _Response_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Response)
	switch tag {
	case 1: // response.success
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Success)
		err := b.DecodeMessage(msg)
		m.Response = &Response_Success{msg}
		return true, err
	case 2: // response.error
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Error)
		err := b.DecodeMessage(msg)
		m.Response = &Response_Error{msg}
		return true, err
	case 3: // response.random_number
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RandomNumberResponse)
		err := b.DecodeMessage(msg)
		m.Response = &Response_RandomNumber{msg}
		return true, err
	case 4: // response.device_info
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DeviceInfoResponse)
		err := b.DecodeMessage(msg)
		m.Response = &Response_DeviceInfo{msg}
		return true, err
	case 5: // response.pub
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PubResponse)
		err := b.DecodeMessage(msg)
		m.Response = &Response_Pub{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Response_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Response)
	// response
	switch x := m.Response.(type) {
	case *Response_Success:
		s := proto.Size(x.Success)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_Error:
		s := proto.Size(x.Error)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_RandomNumber:
		s := proto.Size(x.RandomNumber)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_DeviceInfo:
		s := proto.Size(x.DeviceInfo)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_Pub:
		s := proto.Size(x.Pub)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*Error)(nil), "Error")
	proto.RegisterType((*Success)(nil), "Success")
	proto.RegisterType((*RandomNumberResponse)(nil), "RandomNumberResponse")
	proto.RegisterType((*RandomNumberRequest)(nil), "RandomNumberRequest")
	proto.RegisterType((*DeviceInfoRequest)(nil), "DeviceInfoRequest")
	proto.RegisterType((*DeviceInfoResponse)(nil), "DeviceInfoResponse")
	proto.RegisterType((*SetDeviceNameRequest)(nil), "SetDeviceNameRequest")
	proto.RegisterType((*SetDeviceLanguageRequest)(nil), "SetDeviceLanguageRequest")
	proto.RegisterType((*SetPasswordRequest)(nil), "SetPasswordRequest")
	proto.RegisterType((*CreateBackupRequest)(nil), "CreateBackupRequest")
	proto.RegisterType((*ShowMnemonicRequest)(nil), "ShowMnemonicRequest")
	proto.RegisterType((*BTCPubRequest)(nil), "BTCPubRequest")
	proto.RegisterType((*PubResponse)(nil), "PubResponse")
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterEnum("BTCCoin", BTCCoin_name, BTCCoin_value)
	proto.RegisterEnum("BTCScriptType", BTCScriptType_name, BTCScriptType_value)
	proto.RegisterEnum("BTCOutputType", BTCOutputType_name, BTCOutputType_value)
	proto.RegisterEnum("BTCPubRequest_OutputType", BTCPubRequest_OutputType_name, BTCPubRequest_OutputType_value)
}

func init() { proto.RegisterFile("messages/hww.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 871 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x55, 0xdd, 0x8e, 0x9b, 0x46,
	0x14, 0xc6, 0xc6, 0x36, 0xf6, 0xc1, 0x76, 0xc8, 0x78, 0x13, 0x91, 0x2a, 0x6a, 0x2d, 0x54, 0xa9,
	0xe9, 0x5e, 0xb0, 0x92, 0xab, 0x44, 0x51, 0xdb, 0x9b, 0xd8, 0x1b, 0x89, 0x68, 0x53, 0x2f, 0x1a,
	0x88, 0xb6, 0xad, 0x2a, 0x51, 0x0c, 0xb3, 0xbb, 0x28, 0x0b, 0x43, 0x19, 0x88, 0xb5, 0x79, 0x8b,
	0x3e, 0x65, 0x5f, 0xa0, 0x0f, 0x50, 0xcd, 0x30, 0x60, 0x3b, 0xeb, 0xde, 0x7d, 0xe7, 0xe3, 0xfc,
	0xcc, 0xcc, 0xf9, 0xce, 0x01, 0x50, 0x4a, 0x18, 0x0b, 0x6f, 0x08, 0x3b, 0xbb, 0xdd, 0x6e, 0xed,
	0xbc, 0xa0, 0x25, 0xb5, 0x5e, 0x42, 0xff, 0x6d, 0x51, 0xd0, 0x02, 0x21, 0xe8, 0x45, 0x34, 0x26,
	0x66, 0x67, 0xde, 0x79, 0xd1, 0xc7, 0x02, 0x23, 0x13, 0x34, 0x19, 0x62, 0x76, 0xe7, 0x9d, 0x17,
	0x23, 0xdc, 0x98, 0xd6, 0x08, 0x34, 0xaf, 0x8a, 0x22, 0xc2, 0x98, 0x65, 0xc3, 0x09, 0x0e, 0xb3,
	0x98, 0xa6, 0xeb, 0x2a, 0xdd, 0x90, 0x02, 0x13, 0x96, 0xd3, 0x8c, 0x11, 0xf4, 0x14, 0x06, 0x99,
	0x60, 0x44, 0xca, 0x31, 0x96, 0x96, 0xf5, 0x04, 0x66, 0x87, 0xfe, 0x7f, 0x55, 0x84, 0x95, 0xd6,
	0x0c, 0x1e, 0x9f, 0x93, 0x4f, 0x49, 0x44, 0xde, 0x65, 0xd7, 0xb4, 0x21, 0x63, 0x40, 0xfb, 0xa4,
	0xcc, 0x8c, 0xa0, 0x97, 0x85, 0x69, 0x7d, 0xd4, 0x11, 0x16, 0x18, 0xcd, 0x41, 0x4f, 0xb2, 0xa4,
	0x4c, 0xc2, 0xbb, 0xe4, 0x33, 0x89, 0xc5, 0x71, 0x87, 0x78, 0x9f, 0xe2, 0x97, 0xf9, 0x44, 0x0a,
	0x96, 0xd0, 0xcc, 0x54, 0xeb, 0xcb, 0x48, 0xd3, 0x3a, 0x85, 0x13, 0x8f, 0x94, 0x75, 0xa1, 0x75,
	0x98, 0x12, 0x59, 0xfd, 0x58, 0x1d, 0xeb, 0x15, 0x98, 0xad, 0xef, 0xfb, 0x30, 0xbb, 0xa9, 0xc2,
	0x9b, 0xd6, 0xff, 0x2b, 0x18, 0xde, 0x49, 0x4a, 0xc6, 0xb4, 0xb6, 0x75, 0x02, 0xc8, 0x23, 0xa5,
	0x1b, 0x32, 0xb6, 0xa5, 0x45, 0xdc, 0xdc, 0xef, 0x0f, 0x98, 0xad, 0x0a, 0x12, 0x96, 0x64, 0x19,
	0x46, 0x1f, 0xab, 0xbc, 0x49, 0xf4, 0x1c, 0x46, 0x65, 0x92, 0x12, 0x56, 0x86, 0x69, 0x2e, 0x32,
	0x4d, 0xf0, 0x8e, 0x40, 0xdf, 0xc1, 0x23, 0x6e, 0x7c, 0xa6, 0x19, 0x09, 0xe8, 0xf5, 0x35, 0x23,
	0xa5, 0xb8, 0x6e, 0x1f, 0x4f, 0x1b, 0xfa, 0x52, 0xb0, 0xfc, 0xa5, 0xbd, 0x5b, 0xba, 0xfd, 0x25,
	0x23, 0x29, 0xcd, 0x92, 0xa8, 0x29, 0xfa, 0x77, 0x17, 0x26, 0x4b, 0x7f, 0xe5, 0x56, 0x9b, 0xa6,
	0x9e, 0x09, 0xda, 0x47, 0x72, 0x9f, 0x87, 0xe5, 0xad, 0xd9, 0x99, 0xab, 0x2f, 0x26, 0xb8, 0x31,
	0xd1, 0x19, 0xe8, 0x2c, 0x2a, 0x92, 0xbc, 0x0c, 0xca, 0xfb, 0xbc, 0x56, 0xc1, 0x74, 0x31, 0xb5,
	0x97, 0xfe, 0xca, 0x13, 0xb4, 0x7f, 0x9f, 0x13, 0x0c, 0xac, 0xc5, 0xe8, 0x39, 0x97, 0x51, 0x52,
	0x3f, 0xf1, 0x74, 0x31, 0xe4, 0x9e, 0x2b, 0x9a, 0x64, 0x58, 0xb0, 0xe8, 0x47, 0xd0, 0x69, 0x55,
	0xe6, 0x95, 0x4c, 0xd7, 0x13, 0x4e, 0xcf, 0xec, 0x83, 0xd3, 0xd8, 0x97, 0xc2, 0xa3, 0xce, 0x4c,
	0x5b, 0xcc, 0x0f, 0x19, 0x27, 0x2c, 0xbf, 0x0b, 0xef, 0xcd, 0xbe, 0xe8, 0x6e, 0x63, 0x5a, 0x6f,
	0x00, 0x76, 0x31, 0x68, 0x08, 0x3d, 0xdf, 0xfd, 0xb0, 0x34, 0x14, 0x8e, 0x7e, 0xe5, 0xa8, 0xc3,
	0xd1, 0x6f, 0x1c, 0x75, 0x39, 0xfa, 0x9d, 0x23, 0x15, 0xe9, 0xa0, 0xbd, 0x39, 0x3f, 0xc7, 0x6f,
	0x3d, 0xcf, 0xe8, 0x59, 0xdf, 0x80, 0x2e, 0x4e, 0x20, 0x15, 0x66, 0x80, 0x9a, 0x57, 0x1b, 0xd9,
	0x44, 0x0e, 0xad, 0x7f, 0x54, 0xd0, 0x9a, 0xe7, 0xfa, 0x09, 0x26, 0x85, 0x50, 0x70, 0xb0, 0x27,
	0x70, 0x7d, 0x71, 0x62, 0x1f, 0xd1, 0xb5, 0xa3, 0xe0, 0x71, 0xb1, 0x47, 0xa3, 0xd7, 0xa0, 0xc7,
	0x42, 0x3d, 0x81, 0xd0, 0x56, 0x57, 0x84, 0x3e, 0xb1, 0x8f, 0x09, 0xd0, 0x51, 0x30, 0xc4, 0x2d,
	0x89, 0xce, 0xe1, 0x91, 0x8c, 0x6c, 0x55, 0xa6, 0x8a, 0xe8, 0x67, 0xf6, 0xff, 0x49, 0xd2, 0x51,
	0xf0, 0x34, 0x3e, 0xf8, 0x80, 0x5e, 0xb6, 0xf5, 0x93, 0xec, 0x9a, 0x8a, 0x16, 0xe8, 0x0b, 0x64,
	0x3f, 0x98, 0xbd, 0x5d, 0x71, 0x4e, 0xa2, 0xd7, 0x30, 0x66, 0xa4, 0x0c, 0x72, 0x29, 0x60, 0xd1,
	0x02, 0x7d, 0x31, 0xb3, 0x1f, 0x8a, 0xda, 0x51, 0xb0, 0xce, 0x76, 0x2c, 0x7f, 0xad, 0x48, 0x68,
	0x3c, 0xd8, 0x08, 0x91, 0x9b, 0x03, 0xf9, 0x5a, 0x47, 0x94, 0xcf, 0x5f, 0x2b, 0xda, 0xa3, 0x79,
	0x30, 0xbb, 0xa5, 0xdb, 0x20, 0x95, 0x1a, 0x36, 0x35, 0x19, 0x7c, 0x44, 0xd8, 0x3c, 0x98, 0xed,
	0xd1, 0xe8, 0x7b, 0xd0, 0x36, 0x65, 0x14, 0xf0, 0x4e, 0x0e, 0x45, 0xd8, 0xf4, 0x50, 0x69, 0x8e,
	0x82, 0x07, 0x9b, 0x32, 0x72, 0xab, 0xcd, 0x72, 0x04, 0x5a, 0x21, 0xc7, 0xe3, 0xdf, 0x0e, 0x0c,
	0x5b, 0x21, 0x7c, 0x0b, 0x1a, 0xab, 0xf7, 0x9c, 0x6c, 0xf2, 0xd0, 0x96, 0x7b, 0xcf, 0x51, 0x70,
	0xf3, 0x09, 0x7d, 0x0d, 0x7d, 0xc2, 0x97, 0xa8, 0xec, 0xe6, 0xc0, 0x16, 0x2b, 0xd5, 0x51, 0x70,
	0x4d, 0xa3, 0x9f, 0xbf, 0x14, 0x8c, 0x2a, 0xbb, 0x7e, 0x6c, 0x71, 0x3e, 0x50, 0xcc, 0xab, 0x63,
	0x1d, 0x9b, 0xd9, 0x0f, 0x17, 0xe3, 0x17, 0x2d, 0x9b, 0xd7, 0x22, 0xae, 0x3b, 0x35, 0xb6, 0xf7,
	0xf4, 0xed, 0x28, 0x42, 0xd4, 0x4b, 0x80, 0x61, 0x21, 0xa9, 0xd3, 0x33, 0xd0, 0xe4, 0xac, 0x22,
	0x0d, 0xd4, 0xa5, 0xbf, 0xaa, 0x07, 0xc8, 0xe7, 0xa8, 0xc3, 0xa9, 0xf7, 0xfe, 0xaa, 0x9e, 0x1f,
	0x9f, 0x23, 0xf5, 0xf4, 0x4f, 0xb1, 0x45, 0x76, 0x6b, 0x00, 0x21, 0x98, 0x7a, 0x2b, 0xfc, 0xce,
	0xf5, 0x83, 0x0f, 0xeb, 0x8b, 0xf5, 0xe5, 0xd5, 0xda, 0x50, 0x90, 0x01, 0x63, 0xc9, 0xb9, 0x0b,
	0xf7, 0xc2, 0x31, 0x3a, 0xe8, 0x29, 0xa0, 0x96, 0xb9, 0x72, 0x2f, 0x9c, 0xc0, 0x5d, 0x78, 0x8e,
	0xd1, 0x45, 0x8f, 0x61, 0x72, 0xc0, 0x1b, 0xea, 0xa9, 0x23, 0x2a, 0xec, 0x8d, 0xb6, 0x0e, 0xda,
	0x2e, 0xf5, 0x08, 0xfa, 0x4d, 0xce, 0x21, 0xf4, 0x64, 0x16, 0x80, 0x41, 0x13, 0x5e, 0x3b, 0x5c,
	0x79, 0x8e, 0xd1, 0xdb, 0x0c, 0xc4, 0xcf, 0xee, 0x87, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe7,
	0xa5, 0x34, 0x77, 0x02, 0x07, 0x00, 0x00,
}
