// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages/hww.proto

/*
Package messages is a generated protocol buffer package.

It is generated from these files:
	messages/hww.proto

It has these top-level messages:
	Error
	Success
	RandomNumberResponse
	RandomNumberRequest
	DeviceInfoRequest
	DeviceInfoResponse
	SetDeviceNameRequest
	SetDeviceLanguageRequest
	SetPasswordRequest
	CreateBackupRequest
	ShowMnemonicRequest
	InsertRemoveSDCardRequest
	BTCPubRequest
	PubResponse
	BTCSignInitRequest
	BTCSignNextResponse
	BTCSignInputRequest
	BTCSignOutputRequest
	Request
	Response
*/
package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BTCCoin int32

const (
	BTCCoin_BTC  BTCCoin = 0
	BTCCoin_TBTC BTCCoin = 1
	BTCCoin_LTC  BTCCoin = 2
	BTCCoin_TLTC BTCCoin = 3
)

var BTCCoin_name = map[int32]string{
	0: "BTC",
	1: "TBTC",
	2: "LTC",
	3: "TLTC",
}
var BTCCoin_value = map[string]int32{
	"BTC":  0,
	"TBTC": 1,
	"LTC":  2,
	"TLTC": 3,
}

func (x BTCCoin) String() string {
	return proto.EnumName(BTCCoin_name, int32(x))
}
func (BTCCoin) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type BTCScriptType int32

const (
	BTCScriptType_SCRIPT_UNKNOWN     BTCScriptType = 0
	BTCScriptType_SCRIPT_P2PKH       BTCScriptType = 1
	BTCScriptType_SCRIPT_P2WPKH_P2SH BTCScriptType = 2
	BTCScriptType_SCRIPT_P2WPKH      BTCScriptType = 3
)

var BTCScriptType_name = map[int32]string{
	0: "SCRIPT_UNKNOWN",
	1: "SCRIPT_P2PKH",
	2: "SCRIPT_P2WPKH_P2SH",
	3: "SCRIPT_P2WPKH",
}
var BTCScriptType_value = map[string]int32{
	"SCRIPT_UNKNOWN":     0,
	"SCRIPT_P2PKH":       1,
	"SCRIPT_P2WPKH_P2SH": 2,
	"SCRIPT_P2WPKH":      3,
}

func (x BTCScriptType) String() string {
	return proto.EnumName(BTCScriptType_name, int32(x))
}
func (BTCScriptType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type BTCOutputType int32

const (
	BTCOutputType_UNKNOWN BTCOutputType = 0
	BTCOutputType_P2PKH   BTCOutputType = 1
	BTCOutputType_P2SH    BTCOutputType = 2
	BTCOutputType_P2WPKH  BTCOutputType = 3
	BTCOutputType_P2WSH   BTCOutputType = 4
)

var BTCOutputType_name = map[int32]string{
	0: "UNKNOWN",
	1: "P2PKH",
	2: "P2SH",
	3: "P2WPKH",
	4: "P2WSH",
}
var BTCOutputType_value = map[string]int32{
	"UNKNOWN": 0,
	"P2PKH":   1,
	"P2SH":    2,
	"P2WPKH":  3,
	"P2WSH":   4,
}

func (x BTCOutputType) String() string {
	return proto.EnumName(BTCOutputType_name, int32(x))
}
func (BTCOutputType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type InsertRemoveSDCardRequest_SDCardAction int32

const (
	InsertRemoveSDCardRequest_REMOVE_CARD InsertRemoveSDCardRequest_SDCardAction = 0
	InsertRemoveSDCardRequest_INSERT_CARD InsertRemoveSDCardRequest_SDCardAction = 1
)

var InsertRemoveSDCardRequest_SDCardAction_name = map[int32]string{
	0: "REMOVE_CARD",
	1: "INSERT_CARD",
}
var InsertRemoveSDCardRequest_SDCardAction_value = map[string]int32{
	"REMOVE_CARD": 0,
	"INSERT_CARD": 1,
}

func (x InsertRemoveSDCardRequest_SDCardAction) String() string {
	return proto.EnumName(InsertRemoveSDCardRequest_SDCardAction_name, int32(x))
}
func (InsertRemoveSDCardRequest_SDCardAction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{11, 0}
}

type BTCPubRequest_OutputType int32

const (
	BTCPubRequest_TPUB    BTCPubRequest_OutputType = 0
	BTCPubRequest_XPUB    BTCPubRequest_OutputType = 1
	BTCPubRequest_YPUB    BTCPubRequest_OutputType = 2
	BTCPubRequest_ZPUB    BTCPubRequest_OutputType = 3
	BTCPubRequest_ADDRESS BTCPubRequest_OutputType = 4
)

var BTCPubRequest_OutputType_name = map[int32]string{
	0: "TPUB",
	1: "XPUB",
	2: "YPUB",
	3: "ZPUB",
	4: "ADDRESS",
}
var BTCPubRequest_OutputType_value = map[string]int32{
	"TPUB":    0,
	"XPUB":    1,
	"YPUB":    2,
	"ZPUB":    3,
	"ADDRESS": 4,
}

func (x BTCPubRequest_OutputType) String() string {
	return proto.EnumName(BTCPubRequest_OutputType_name, int32(x))
}
func (BTCPubRequest_OutputType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{12, 0} }

type BTCSignNextResponse_Type int32

const (
	BTCSignNextResponse_INPUT  BTCSignNextResponse_Type = 0
	BTCSignNextResponse_OUTPUT BTCSignNextResponse_Type = 1
	BTCSignNextResponse_DONE   BTCSignNextResponse_Type = 2
)

var BTCSignNextResponse_Type_name = map[int32]string{
	0: "INPUT",
	1: "OUTPUT",
	2: "DONE",
}
var BTCSignNextResponse_Type_value = map[string]int32{
	"INPUT":  0,
	"OUTPUT": 1,
	"DONE":   2,
}

func (x BTCSignNextResponse_Type) String() string {
	return proto.EnumName(BTCSignNextResponse_Type_name, int32(x))
}
func (BTCSignNextResponse_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{15, 0} }

type Error struct {
	Code    int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Success struct {
}

func (m *Success) Reset()                    { *m = Success{} }
func (m *Success) String() string            { return proto.CompactTextString(m) }
func (*Success) ProtoMessage()               {}
func (*Success) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type RandomNumberResponse struct {
	Number []byte `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (m *RandomNumberResponse) Reset()                    { *m = RandomNumberResponse{} }
func (m *RandomNumberResponse) String() string            { return proto.CompactTextString(m) }
func (*RandomNumberResponse) ProtoMessage()               {}
func (*RandomNumberResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RandomNumberResponse) GetNumber() []byte {
	if m != nil {
		return m.Number
	}
	return nil
}

type RandomNumberRequest struct {
}

func (m *RandomNumberRequest) Reset()                    { *m = RandomNumberRequest{} }
func (m *RandomNumberRequest) String() string            { return proto.CompactTextString(m) }
func (*RandomNumberRequest) ProtoMessage()               {}
func (*RandomNumberRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type DeviceInfoRequest struct {
}

func (m *DeviceInfoRequest) Reset()                    { *m = DeviceInfoRequest{} }
func (m *DeviceInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*DeviceInfoRequest) ProtoMessage()               {}
func (*DeviceInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type DeviceInfoResponse struct {
	Name        string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Initialized bool   `protobuf:"varint,2,opt,name=initialized" json:"initialized,omitempty"`
	Version     string `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
}

func (m *DeviceInfoResponse) Reset()                    { *m = DeviceInfoResponse{} }
func (m *DeviceInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*DeviceInfoResponse) ProtoMessage()               {}
func (*DeviceInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DeviceInfoResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeviceInfoResponse) GetInitialized() bool {
	if m != nil {
		return m.Initialized
	}
	return false
}

func (m *DeviceInfoResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type SetDeviceNameRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *SetDeviceNameRequest) Reset()                    { *m = SetDeviceNameRequest{} }
func (m *SetDeviceNameRequest) String() string            { return proto.CompactTextString(m) }
func (*SetDeviceNameRequest) ProtoMessage()               {}
func (*SetDeviceNameRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SetDeviceNameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SetDeviceLanguageRequest struct {
	Language string `protobuf:"bytes,1,opt,name=language" json:"language,omitempty"`
}

func (m *SetDeviceLanguageRequest) Reset()                    { *m = SetDeviceLanguageRequest{} }
func (m *SetDeviceLanguageRequest) String() string            { return proto.CompactTextString(m) }
func (*SetDeviceLanguageRequest) ProtoMessage()               {}
func (*SetDeviceLanguageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SetDeviceLanguageRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

type SetPasswordRequest struct {
}

func (m *SetPasswordRequest) Reset()                    { *m = SetPasswordRequest{} }
func (m *SetPasswordRequest) String() string            { return proto.CompactTextString(m) }
func (*SetPasswordRequest) ProtoMessage()               {}
func (*SetPasswordRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type CreateBackupRequest struct {
	// TODO add backup creation args
	Timestamp      uint32 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	TimezoneOffset int32  `protobuf:"varint,2,opt,name=timezone_offset,json=timezoneOffset" json:"timezone_offset,omitempty"`
}

func (m *CreateBackupRequest) Reset()                    { *m = CreateBackupRequest{} }
func (m *CreateBackupRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateBackupRequest) ProtoMessage()               {}
func (*CreateBackupRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *CreateBackupRequest) GetTimestamp() uint32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *CreateBackupRequest) GetTimezoneOffset() int32 {
	if m != nil {
		return m.TimezoneOffset
	}
	return 0
}

type ShowMnemonicRequest struct {
}

func (m *ShowMnemonicRequest) Reset()                    { *m = ShowMnemonicRequest{} }
func (m *ShowMnemonicRequest) String() string            { return proto.CompactTextString(m) }
func (*ShowMnemonicRequest) ProtoMessage()               {}
func (*ShowMnemonicRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type InsertRemoveSDCardRequest struct {
	Action InsertRemoveSDCardRequest_SDCardAction `protobuf:"varint,1,opt,name=action,enum=InsertRemoveSDCardRequest_SDCardAction" json:"action,omitempty"`
}

func (m *InsertRemoveSDCardRequest) Reset()                    { *m = InsertRemoveSDCardRequest{} }
func (m *InsertRemoveSDCardRequest) String() string            { return proto.CompactTextString(m) }
func (*InsertRemoveSDCardRequest) ProtoMessage()               {}
func (*InsertRemoveSDCardRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *InsertRemoveSDCardRequest) GetAction() InsertRemoveSDCardRequest_SDCardAction {
	if m != nil {
		return m.Action
	}
	return InsertRemoveSDCardRequest_REMOVE_CARD
}

type BTCPubRequest struct {
	Keypath    []uint32                 `protobuf:"varint,1,rep,packed,name=keypath" json:"keypath,omitempty"`
	ScriptType BTCScriptType            `protobuf:"varint,2,opt,name=script_type,json=scriptType,enum=BTCScriptType" json:"script_type,omitempty"`
	Coin       BTCCoin                  `protobuf:"varint,3,opt,name=coin,enum=BTCCoin" json:"coin,omitempty"`
	OutputType BTCPubRequest_OutputType `protobuf:"varint,4,opt,name=output_type,json=outputType,enum=BTCPubRequest_OutputType" json:"output_type,omitempty"`
	Display    bool                     `protobuf:"varint,5,opt,name=display" json:"display,omitempty"`
}

func (m *BTCPubRequest) Reset()                    { *m = BTCPubRequest{} }
func (m *BTCPubRequest) String() string            { return proto.CompactTextString(m) }
func (*BTCPubRequest) ProtoMessage()               {}
func (*BTCPubRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *BTCPubRequest) GetKeypath() []uint32 {
	if m != nil {
		return m.Keypath
	}
	return nil
}

func (m *BTCPubRequest) GetScriptType() BTCScriptType {
	if m != nil {
		return m.ScriptType
	}
	return BTCScriptType_SCRIPT_UNKNOWN
}

func (m *BTCPubRequest) GetCoin() BTCCoin {
	if m != nil {
		return m.Coin
	}
	return BTCCoin_BTC
}

func (m *BTCPubRequest) GetOutputType() BTCPubRequest_OutputType {
	if m != nil {
		return m.OutputType
	}
	return BTCPubRequest_TPUB
}

func (m *BTCPubRequest) GetDisplay() bool {
	if m != nil {
		return m.Display
	}
	return false
}

type PubResponse struct {
	Pub string `protobuf:"bytes,1,opt,name=pub" json:"pub,omitempty"`
}

func (m *PubResponse) Reset()                    { *m = PubResponse{} }
func (m *PubResponse) String() string            { return proto.CompactTextString(m) }
func (*PubResponse) ProtoMessage()               {}
func (*PubResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *PubResponse) GetPub() string {
	if m != nil {
		return m.Pub
	}
	return ""
}

type BTCSignInitRequest struct {
	Coin         BTCCoin       `protobuf:"varint,1,opt,name=coin,enum=BTCCoin" json:"coin,omitempty"`
	ScriptType   BTCScriptType `protobuf:"varint,2,opt,name=script_type,json=scriptType,enum=BTCScriptType" json:"script_type,omitempty"`
	Bip44Account uint32        `protobuf:"varint,3,opt,name=bip44_account,json=bip44Account" json:"bip44_account,omitempty"`
	Version      uint32        `protobuf:"varint,4,opt,name=version" json:"version,omitempty"`
	NumInputs    uint32        `protobuf:"varint,5,opt,name=num_inputs,json=numInputs" json:"num_inputs,omitempty"`
	NumOutputs   uint32        `protobuf:"varint,6,opt,name=num_outputs,json=numOutputs" json:"num_outputs,omitempty"`
	Locktime     uint32        `protobuf:"varint,7,opt,name=locktime" json:"locktime,omitempty"`
}

func (m *BTCSignInitRequest) Reset()                    { *m = BTCSignInitRequest{} }
func (m *BTCSignInitRequest) String() string            { return proto.CompactTextString(m) }
func (*BTCSignInitRequest) ProtoMessage()               {}
func (*BTCSignInitRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *BTCSignInitRequest) GetCoin() BTCCoin {
	if m != nil {
		return m.Coin
	}
	return BTCCoin_BTC
}

func (m *BTCSignInitRequest) GetScriptType() BTCScriptType {
	if m != nil {
		return m.ScriptType
	}
	return BTCScriptType_SCRIPT_UNKNOWN
}

func (m *BTCSignInitRequest) GetBip44Account() uint32 {
	if m != nil {
		return m.Bip44Account
	}
	return 0
}

func (m *BTCSignInitRequest) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *BTCSignInitRequest) GetNumInputs() uint32 {
	if m != nil {
		return m.NumInputs
	}
	return 0
}

func (m *BTCSignInitRequest) GetNumOutputs() uint32 {
	if m != nil {
		return m.NumOutputs
	}
	return 0
}

func (m *BTCSignInitRequest) GetLocktime() uint32 {
	if m != nil {
		return m.Locktime
	}
	return 0
}

type BTCSignNextResponse struct {
	Type         BTCSignNextResponse_Type `protobuf:"varint,1,opt,name=type,enum=BTCSignNextResponse_Type" json:"type,omitempty"`
	Index        uint32                   `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
	HasSignature bool                     `protobuf:"varint,3,opt,name=has_signature,json=hasSignature" json:"has_signature,omitempty"`
	// 64 bytes (32 bytes big endian R, 32 bytes big endian S). Only if has_signature is true.
	Signature []byte `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *BTCSignNextResponse) Reset()                    { *m = BTCSignNextResponse{} }
func (m *BTCSignNextResponse) String() string            { return proto.CompactTextString(m) }
func (*BTCSignNextResponse) ProtoMessage()               {}
func (*BTCSignNextResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *BTCSignNextResponse) GetType() BTCSignNextResponse_Type {
	if m != nil {
		return m.Type
	}
	return BTCSignNextResponse_INPUT
}

func (m *BTCSignNextResponse) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *BTCSignNextResponse) GetHasSignature() bool {
	if m != nil {
		return m.HasSignature
	}
	return false
}

func (m *BTCSignNextResponse) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type BTCSignInputRequest struct {
	PrevOutHash  []byte   `protobuf:"bytes,1,opt,name=prevOutHash,proto3" json:"prevOutHash,omitempty"`
	PrevOutIndex uint32   `protobuf:"varint,2,opt,name=prevOutIndex" json:"prevOutIndex,omitempty"`
	PrevOutValue uint64   `protobuf:"varint,3,opt,name=prevOutValue" json:"prevOutValue,omitempty"`
	Sequence     uint32   `protobuf:"varint,4,opt,name=sequence" json:"sequence,omitempty"`
	Keypath      []uint32 `protobuf:"varint,6,rep,packed,name=keypath" json:"keypath,omitempty"`
}

func (m *BTCSignInputRequest) Reset()                    { *m = BTCSignInputRequest{} }
func (m *BTCSignInputRequest) String() string            { return proto.CompactTextString(m) }
func (*BTCSignInputRequest) ProtoMessage()               {}
func (*BTCSignInputRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *BTCSignInputRequest) GetPrevOutHash() []byte {
	if m != nil {
		return m.PrevOutHash
	}
	return nil
}

func (m *BTCSignInputRequest) GetPrevOutIndex() uint32 {
	if m != nil {
		return m.PrevOutIndex
	}
	return 0
}

func (m *BTCSignInputRequest) GetPrevOutValue() uint64 {
	if m != nil {
		return m.PrevOutValue
	}
	return 0
}

func (m *BTCSignInputRequest) GetSequence() uint32 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *BTCSignInputRequest) GetKeypath() []uint32 {
	if m != nil {
		return m.Keypath
	}
	return nil
}

type BTCSignOutputRequest struct {
	Ours bool          `protobuf:"varint,1,opt,name=ours" json:"ours,omitempty"`
	Type BTCOutputType `protobuf:"varint,2,opt,name=type,enum=BTCOutputType" json:"type,omitempty"`
	// 20 bytes for p2pkh, p2sh, pw2wpkh. 32 bytes for p2wsh.
	Value   uint64   `protobuf:"varint,3,opt,name=value" json:"value,omitempty"`
	Hash    []byte   `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	Keypath []uint32 `protobuf:"varint,5,rep,packed,name=keypath" json:"keypath,omitempty"`
}

func (m *BTCSignOutputRequest) Reset()                    { *m = BTCSignOutputRequest{} }
func (m *BTCSignOutputRequest) String() string            { return proto.CompactTextString(m) }
func (*BTCSignOutputRequest) ProtoMessage()               {}
func (*BTCSignOutputRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *BTCSignOutputRequest) GetOurs() bool {
	if m != nil {
		return m.Ours
	}
	return false
}

func (m *BTCSignOutputRequest) GetType() BTCOutputType {
	if m != nil {
		return m.Type
	}
	return BTCOutputType_UNKNOWN
}

func (m *BTCSignOutputRequest) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *BTCSignOutputRequest) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BTCSignOutputRequest) GetKeypath() []uint32 {
	if m != nil {
		return m.Keypath
	}
	return nil
}

type Request struct {
	// Types that are valid to be assigned to Request:
	//	*Request_RandomNumber
	//	*Request_DeviceName
	//	*Request_DeviceLanguage
	//	*Request_DeviceInfo
	//	*Request_SetPassword
	//	*Request_CreateBackup
	//	*Request_ShowMnemonic
	//	*Request_BtcPub
	//	*Request_BtcSignInit
	//	*Request_BtcSignInput
	//	*Request_BtcSignOutput
	//	*Request_InsertRemoveSdcard
	Request isRequest_Request `protobuf_oneof:"request"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

type isRequest_Request interface{ isRequest_Request() }

type Request_RandomNumber struct {
	RandomNumber *RandomNumberRequest `protobuf:"bytes,1,opt,name=random_number,json=randomNumber,oneof"`
}
type Request_DeviceName struct {
	DeviceName *SetDeviceNameRequest `protobuf:"bytes,2,opt,name=device_name,json=deviceName,oneof"`
}
type Request_DeviceLanguage struct {
	DeviceLanguage *SetDeviceLanguageRequest `protobuf:"bytes,3,opt,name=device_language,json=deviceLanguage,oneof"`
}
type Request_DeviceInfo struct {
	DeviceInfo *DeviceInfoRequest `protobuf:"bytes,4,opt,name=device_info,json=deviceInfo,oneof"`
}
type Request_SetPassword struct {
	SetPassword *SetPasswordRequest `protobuf:"bytes,5,opt,name=set_password,json=setPassword,oneof"`
}
type Request_CreateBackup struct {
	CreateBackup *CreateBackupRequest `protobuf:"bytes,6,opt,name=create_backup,json=createBackup,oneof"`
}
type Request_ShowMnemonic struct {
	ShowMnemonic *ShowMnemonicRequest `protobuf:"bytes,7,opt,name=show_mnemonic,json=showMnemonic,oneof"`
}
type Request_BtcPub struct {
	BtcPub *BTCPubRequest `protobuf:"bytes,8,opt,name=btc_pub,json=btcPub,oneof"`
}
type Request_BtcSignInit struct {
	BtcSignInit *BTCSignInitRequest `protobuf:"bytes,9,opt,name=btc_sign_init,json=btcSignInit,oneof"`
}
type Request_BtcSignInput struct {
	BtcSignInput *BTCSignInputRequest `protobuf:"bytes,10,opt,name=btc_sign_input,json=btcSignInput,oneof"`
}
type Request_BtcSignOutput struct {
	BtcSignOutput *BTCSignOutputRequest `protobuf:"bytes,11,opt,name=btc_sign_output,json=btcSignOutput,oneof"`
}
type Request_InsertRemoveSdcard struct {
	InsertRemoveSdcard *InsertRemoveSDCardRequest `protobuf:"bytes,12,opt,name=insert_remove_sdcard,json=insertRemoveSdcard,oneof"`
}

func (*Request_RandomNumber) isRequest_Request()       {}
func (*Request_DeviceName) isRequest_Request()         {}
func (*Request_DeviceLanguage) isRequest_Request()     {}
func (*Request_DeviceInfo) isRequest_Request()         {}
func (*Request_SetPassword) isRequest_Request()        {}
func (*Request_CreateBackup) isRequest_Request()       {}
func (*Request_ShowMnemonic) isRequest_Request()       {}
func (*Request_BtcPub) isRequest_Request()             {}
func (*Request_BtcSignInit) isRequest_Request()        {}
func (*Request_BtcSignInput) isRequest_Request()       {}
func (*Request_BtcSignOutput) isRequest_Request()      {}
func (*Request_InsertRemoveSdcard) isRequest_Request() {}

func (m *Request) GetRequest() isRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *Request) GetRandomNumber() *RandomNumberRequest {
	if x, ok := m.GetRequest().(*Request_RandomNumber); ok {
		return x.RandomNumber
	}
	return nil
}

func (m *Request) GetDeviceName() *SetDeviceNameRequest {
	if x, ok := m.GetRequest().(*Request_DeviceName); ok {
		return x.DeviceName
	}
	return nil
}

func (m *Request) GetDeviceLanguage() *SetDeviceLanguageRequest {
	if x, ok := m.GetRequest().(*Request_DeviceLanguage); ok {
		return x.DeviceLanguage
	}
	return nil
}

func (m *Request) GetDeviceInfo() *DeviceInfoRequest {
	if x, ok := m.GetRequest().(*Request_DeviceInfo); ok {
		return x.DeviceInfo
	}
	return nil
}

func (m *Request) GetSetPassword() *SetPasswordRequest {
	if x, ok := m.GetRequest().(*Request_SetPassword); ok {
		return x.SetPassword
	}
	return nil
}

func (m *Request) GetCreateBackup() *CreateBackupRequest {
	if x, ok := m.GetRequest().(*Request_CreateBackup); ok {
		return x.CreateBackup
	}
	return nil
}

func (m *Request) GetShowMnemonic() *ShowMnemonicRequest {
	if x, ok := m.GetRequest().(*Request_ShowMnemonic); ok {
		return x.ShowMnemonic
	}
	return nil
}

func (m *Request) GetBtcPub() *BTCPubRequest {
	if x, ok := m.GetRequest().(*Request_BtcPub); ok {
		return x.BtcPub
	}
	return nil
}

func (m *Request) GetBtcSignInit() *BTCSignInitRequest {
	if x, ok := m.GetRequest().(*Request_BtcSignInit); ok {
		return x.BtcSignInit
	}
	return nil
}

func (m *Request) GetBtcSignInput() *BTCSignInputRequest {
	if x, ok := m.GetRequest().(*Request_BtcSignInput); ok {
		return x.BtcSignInput
	}
	return nil
}

func (m *Request) GetBtcSignOutput() *BTCSignOutputRequest {
	if x, ok := m.GetRequest().(*Request_BtcSignOutput); ok {
		return x.BtcSignOutput
	}
	return nil
}

func (m *Request) GetInsertRemoveSdcard() *InsertRemoveSDCardRequest {
	if x, ok := m.GetRequest().(*Request_InsertRemoveSdcard); ok {
		return x.InsertRemoveSdcard
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Request) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Request_OneofMarshaler, _Request_OneofUnmarshaler, _Request_OneofSizer, []interface{}{
		(*Request_RandomNumber)(nil),
		(*Request_DeviceName)(nil),
		(*Request_DeviceLanguage)(nil),
		(*Request_DeviceInfo)(nil),
		(*Request_SetPassword)(nil),
		(*Request_CreateBackup)(nil),
		(*Request_ShowMnemonic)(nil),
		(*Request_BtcPub)(nil),
		(*Request_BtcSignInit)(nil),
		(*Request_BtcSignInput)(nil),
		(*Request_BtcSignOutput)(nil),
		(*Request_InsertRemoveSdcard)(nil),
	}
}

func _Request_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Request)
	// request
	switch x := m.Request.(type) {
	case *Request_RandomNumber:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RandomNumber); err != nil {
			return err
		}
	case *Request_DeviceName:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DeviceName); err != nil {
			return err
		}
	case *Request_DeviceLanguage:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DeviceLanguage); err != nil {
			return err
		}
	case *Request_DeviceInfo:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DeviceInfo); err != nil {
			return err
		}
	case *Request_SetPassword:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SetPassword); err != nil {
			return err
		}
	case *Request_CreateBackup:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CreateBackup); err != nil {
			return err
		}
	case *Request_ShowMnemonic:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ShowMnemonic); err != nil {
			return err
		}
	case *Request_BtcPub:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BtcPub); err != nil {
			return err
		}
	case *Request_BtcSignInit:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BtcSignInit); err != nil {
			return err
		}
	case *Request_BtcSignInput:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BtcSignInput); err != nil {
			return err
		}
	case *Request_BtcSignOutput:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BtcSignOutput); err != nil {
			return err
		}
	case *Request_InsertRemoveSdcard:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.InsertRemoveSdcard); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Request.Request has unexpected type %T", x)
	}
	return nil
}

func _Request_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Request)
	switch tag {
	case 1: // request.random_number
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RandomNumberRequest)
		err := b.DecodeMessage(msg)
		m.Request = &Request_RandomNumber{msg}
		return true, err
	case 2: // request.device_name
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SetDeviceNameRequest)
		err := b.DecodeMessage(msg)
		m.Request = &Request_DeviceName{msg}
		return true, err
	case 3: // request.device_language
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SetDeviceLanguageRequest)
		err := b.DecodeMessage(msg)
		m.Request = &Request_DeviceLanguage{msg}
		return true, err
	case 4: // request.device_info
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DeviceInfoRequest)
		err := b.DecodeMessage(msg)
		m.Request = &Request_DeviceInfo{msg}
		return true, err
	case 5: // request.set_password
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SetPasswordRequest)
		err := b.DecodeMessage(msg)
		m.Request = &Request_SetPassword{msg}
		return true, err
	case 6: // request.create_backup
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CreateBackupRequest)
		err := b.DecodeMessage(msg)
		m.Request = &Request_CreateBackup{msg}
		return true, err
	case 7: // request.show_mnemonic
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ShowMnemonicRequest)
		err := b.DecodeMessage(msg)
		m.Request = &Request_ShowMnemonic{msg}
		return true, err
	case 8: // request.btc_pub
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BTCPubRequest)
		err := b.DecodeMessage(msg)
		m.Request = &Request_BtcPub{msg}
		return true, err
	case 9: // request.btc_sign_init
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BTCSignInitRequest)
		err := b.DecodeMessage(msg)
		m.Request = &Request_BtcSignInit{msg}
		return true, err
	case 10: // request.btc_sign_input
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BTCSignInputRequest)
		err := b.DecodeMessage(msg)
		m.Request = &Request_BtcSignInput{msg}
		return true, err
	case 11: // request.btc_sign_output
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BTCSignOutputRequest)
		err := b.DecodeMessage(msg)
		m.Request = &Request_BtcSignOutput{msg}
		return true, err
	case 12: // request.insert_remove_sdcard
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(InsertRemoveSDCardRequest)
		err := b.DecodeMessage(msg)
		m.Request = &Request_InsertRemoveSdcard{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Request_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Request)
	// request
	switch x := m.Request.(type) {
	case *Request_RandomNumber:
		s := proto.Size(x.RandomNumber)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_DeviceName:
		s := proto.Size(x.DeviceName)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_DeviceLanguage:
		s := proto.Size(x.DeviceLanguage)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_DeviceInfo:
		s := proto.Size(x.DeviceInfo)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_SetPassword:
		s := proto.Size(x.SetPassword)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_CreateBackup:
		s := proto.Size(x.CreateBackup)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_ShowMnemonic:
		s := proto.Size(x.ShowMnemonic)
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_BtcPub:
		s := proto.Size(x.BtcPub)
		n += proto.SizeVarint(8<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_BtcSignInit:
		s := proto.Size(x.BtcSignInit)
		n += proto.SizeVarint(9<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_BtcSignInput:
		s := proto.Size(x.BtcSignInput)
		n += proto.SizeVarint(10<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_BtcSignOutput:
		s := proto.Size(x.BtcSignOutput)
		n += proto.SizeVarint(11<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_InsertRemoveSdcard:
		s := proto.Size(x.InsertRemoveSdcard)
		n += proto.SizeVarint(12<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Response struct {
	// Types that are valid to be assigned to Response:
	//	*Response_Success
	//	*Response_Error
	//	*Response_RandomNumber
	//	*Response_DeviceInfo
	//	*Response_Pub
	//	*Response_BtcSignNext
	Response isResponse_Response `protobuf_oneof:"response"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

type isResponse_Response interface{ isResponse_Response() }

type Response_Success struct {
	Success *Success `protobuf:"bytes,1,opt,name=success,oneof"`
}
type Response_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,oneof"`
}
type Response_RandomNumber struct {
	RandomNumber *RandomNumberResponse `protobuf:"bytes,3,opt,name=random_number,json=randomNumber,oneof"`
}
type Response_DeviceInfo struct {
	DeviceInfo *DeviceInfoResponse `protobuf:"bytes,4,opt,name=device_info,json=deviceInfo,oneof"`
}
type Response_Pub struct {
	Pub *PubResponse `protobuf:"bytes,5,opt,name=pub,oneof"`
}
type Response_BtcSignNext struct {
	BtcSignNext *BTCSignNextResponse `protobuf:"bytes,6,opt,name=btc_sign_next,json=btcSignNext,oneof"`
}

func (*Response_Success) isResponse_Response()      {}
func (*Response_Error) isResponse_Response()        {}
func (*Response_RandomNumber) isResponse_Response() {}
func (*Response_DeviceInfo) isResponse_Response()   {}
func (*Response_Pub) isResponse_Response()          {}
func (*Response_BtcSignNext) isResponse_Response()  {}

func (m *Response) GetResponse() isResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *Response) GetSuccess() *Success {
	if x, ok := m.GetResponse().(*Response_Success); ok {
		return x.Success
	}
	return nil
}

func (m *Response) GetError() *Error {
	if x, ok := m.GetResponse().(*Response_Error); ok {
		return x.Error
	}
	return nil
}

func (m *Response) GetRandomNumber() *RandomNumberResponse {
	if x, ok := m.GetResponse().(*Response_RandomNumber); ok {
		return x.RandomNumber
	}
	return nil
}

func (m *Response) GetDeviceInfo() *DeviceInfoResponse {
	if x, ok := m.GetResponse().(*Response_DeviceInfo); ok {
		return x.DeviceInfo
	}
	return nil
}

func (m *Response) GetPub() *PubResponse {
	if x, ok := m.GetResponse().(*Response_Pub); ok {
		return x.Pub
	}
	return nil
}

func (m *Response) GetBtcSignNext() *BTCSignNextResponse {
	if x, ok := m.GetResponse().(*Response_BtcSignNext); ok {
		return x.BtcSignNext
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Response) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Response_OneofMarshaler, _Response_OneofUnmarshaler, _Response_OneofSizer, []interface{}{
		(*Response_Success)(nil),
		(*Response_Error)(nil),
		(*Response_RandomNumber)(nil),
		(*Response_DeviceInfo)(nil),
		(*Response_Pub)(nil),
		(*Response_BtcSignNext)(nil),
	}
}

func _Response_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Response)
	// response
	switch x := m.Response.(type) {
	case *Response_Success:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Success); err != nil {
			return err
		}
	case *Response_Error:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Error); err != nil {
			return err
		}
	case *Response_RandomNumber:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RandomNumber); err != nil {
			return err
		}
	case *Response_DeviceInfo:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DeviceInfo); err != nil {
			return err
		}
	case *Response_Pub:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Pub); err != nil {
			return err
		}
	case *Response_BtcSignNext:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BtcSignNext); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Response.Response has unexpected type %T", x)
	}
	return nil
}

func _Response_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Response)
	switch tag {
	case 1: // response.success
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Success)
		err := b.DecodeMessage(msg)
		m.Response = &Response_Success{msg}
		return true, err
	case 2: // response.error
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Error)
		err := b.DecodeMessage(msg)
		m.Response = &Response_Error{msg}
		return true, err
	case 3: // response.random_number
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RandomNumberResponse)
		err := b.DecodeMessage(msg)
		m.Response = &Response_RandomNumber{msg}
		return true, err
	case 4: // response.device_info
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DeviceInfoResponse)
		err := b.DecodeMessage(msg)
		m.Response = &Response_DeviceInfo{msg}
		return true, err
	case 5: // response.pub
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PubResponse)
		err := b.DecodeMessage(msg)
		m.Response = &Response_Pub{msg}
		return true, err
	case 6: // response.btc_sign_next
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BTCSignNextResponse)
		err := b.DecodeMessage(msg)
		m.Response = &Response_BtcSignNext{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Response_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Response)
	// response
	switch x := m.Response.(type) {
	case *Response_Success:
		s := proto.Size(x.Success)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_Error:
		s := proto.Size(x.Error)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_RandomNumber:
		s := proto.Size(x.RandomNumber)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_DeviceInfo:
		s := proto.Size(x.DeviceInfo)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_Pub:
		s := proto.Size(x.Pub)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_BtcSignNext:
		s := proto.Size(x.BtcSignNext)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*Error)(nil), "Error")
	proto.RegisterType((*Success)(nil), "Success")
	proto.RegisterType((*RandomNumberResponse)(nil), "RandomNumberResponse")
	proto.RegisterType((*RandomNumberRequest)(nil), "RandomNumberRequest")
	proto.RegisterType((*DeviceInfoRequest)(nil), "DeviceInfoRequest")
	proto.RegisterType((*DeviceInfoResponse)(nil), "DeviceInfoResponse")
	proto.RegisterType((*SetDeviceNameRequest)(nil), "SetDeviceNameRequest")
	proto.RegisterType((*SetDeviceLanguageRequest)(nil), "SetDeviceLanguageRequest")
	proto.RegisterType((*SetPasswordRequest)(nil), "SetPasswordRequest")
	proto.RegisterType((*CreateBackupRequest)(nil), "CreateBackupRequest")
	proto.RegisterType((*ShowMnemonicRequest)(nil), "ShowMnemonicRequest")
	proto.RegisterType((*InsertRemoveSDCardRequest)(nil), "InsertRemoveSDCardRequest")
	proto.RegisterType((*BTCPubRequest)(nil), "BTCPubRequest")
	proto.RegisterType((*PubResponse)(nil), "PubResponse")
	proto.RegisterType((*BTCSignInitRequest)(nil), "BTCSignInitRequest")
	proto.RegisterType((*BTCSignNextResponse)(nil), "BTCSignNextResponse")
	proto.RegisterType((*BTCSignInputRequest)(nil), "BTCSignInputRequest")
	proto.RegisterType((*BTCSignOutputRequest)(nil), "BTCSignOutputRequest")
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterEnum("BTCCoin", BTCCoin_name, BTCCoin_value)
	proto.RegisterEnum("BTCScriptType", BTCScriptType_name, BTCScriptType_value)
	proto.RegisterEnum("BTCOutputType", BTCOutputType_name, BTCOutputType_value)
	proto.RegisterEnum("InsertRemoveSDCardRequest_SDCardAction", InsertRemoveSDCardRequest_SDCardAction_name, InsertRemoveSDCardRequest_SDCardAction_value)
	proto.RegisterEnum("BTCPubRequest_OutputType", BTCPubRequest_OutputType_name, BTCPubRequest_OutputType_value)
	proto.RegisterEnum("BTCSignNextResponse_Type", BTCSignNextResponse_Type_name, BTCSignNextResponse_Type_value)
}

func init() { proto.RegisterFile("messages/hww.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xef, 0x6e, 0xdb, 0x46,
	0x12, 0x27, 0xad, 0xff, 0x43, 0x49, 0x56, 0xd6, 0x4a, 0xc0, 0x04, 0xb9, 0x8b, 0xc1, 0x3b, 0x20,
	0x39, 0x03, 0xc7, 0x14, 0x6a, 0x12, 0xa4, 0x69, 0x80, 0xc2, 0x92, 0x0c, 0x50, 0x48, 0x22, 0x09,
	0x2b, 0x39, 0x69, 0x8b, 0x02, 0x2c, 0x45, 0xad, 0x2d, 0x22, 0x16, 0xc9, 0x72, 0x49, 0x3b, 0xce,
	0x43, 0x14, 0x68, 0x9f, 0xa4, 0x5f, 0xfa, 0x0a, 0x7d, 0x9f, 0xbe, 0x40, 0x51, 0xec, 0x70, 0x49,
	0x51, 0xb1, 0xf2, 0xa1, 0xdf, 0x66, 0x7e, 0x3b, 0xb3, 0x3b, 0x33, 0x3b, 0xb3, 0xbf, 0x05, 0xb2,
	0x66, 0x9c, 0x3b, 0xe7, 0x8c, 0x3f, 0x5e, 0x5d, 0x5d, 0x99, 0x61, 0x14, 0xc4, 0x81, 0xf1, 0x14,
	0x2a, 0x27, 0x51, 0x14, 0x44, 0x84, 0x40, 0xd9, 0x0d, 0x96, 0x4c, 0x57, 0x0f, 0xd5, 0x47, 0x15,
	0x8a, 0x32, 0xd1, 0xa1, 0x26, 0x5d, 0xf4, 0xbd, 0x43, 0xf5, 0x51, 0x83, 0x66, 0xaa, 0xd1, 0x80,
	0xda, 0x2c, 0x71, 0x5d, 0xc6, 0xb9, 0x61, 0x42, 0x97, 0x3a, 0xfe, 0x32, 0x58, 0x8f, 0x93, 0xf5,
	0x82, 0x45, 0x94, 0xf1, 0x30, 0xf0, 0x39, 0x23, 0x77, 0xa0, 0xea, 0x23, 0x82, 0x5b, 0x36, 0xa9,
	0xd4, 0x8c, 0xdb, 0x70, 0xb0, 0x6d, 0xff, 0x53, 0xc2, 0x78, 0x6c, 0x1c, 0xc0, 0xad, 0x21, 0xbb,
	0xf4, 0x5c, 0x36, 0xf2, 0xcf, 0x82, 0x0c, 0x5c, 0x02, 0x29, 0x82, 0x72, 0x67, 0x02, 0x65, 0xdf,
	0x59, 0xa7, 0xa1, 0x36, 0x28, 0xca, 0xe4, 0x10, 0x34, 0xcf, 0xf7, 0x62, 0xcf, 0xb9, 0xf0, 0x3e,
	0xb2, 0x25, 0x86, 0x5b, 0xa7, 0x45, 0x48, 0x24, 0x73, 0xc9, 0x22, 0xee, 0x05, 0xbe, 0x5e, 0x4a,
	0x93, 0x91, 0xaa, 0x71, 0x04, 0xdd, 0x19, 0x8b, 0xd3, 0x83, 0xc6, 0xce, 0x9a, 0xc9, 0xd3, 0x77,
	0x9d, 0x63, 0x3c, 0x03, 0x3d, 0xb7, 0x7d, 0xed, 0xf8, 0xe7, 0x89, 0x73, 0x9e, 0xdb, 0xdf, 0x83,
	0xfa, 0x85, 0x84, 0xa4, 0x4f, 0xae, 0x1b, 0x5d, 0x20, 0x33, 0x16, 0x4f, 0x1d, 0xce, 0xaf, 0x82,
	0x68, 0x99, 0xe5, 0xf7, 0x03, 0x1c, 0x0c, 0x22, 0xe6, 0xc4, 0xac, 0xef, 0xb8, 0xef, 0x93, 0x30,
	0xdb, 0xe8, 0x3e, 0x34, 0x62, 0x6f, 0xcd, 0x78, 0xec, 0xac, 0x43, 0xdc, 0xa9, 0x45, 0x37, 0x00,
	0x79, 0x08, 0xfb, 0x42, 0xf9, 0x18, 0xf8, 0xcc, 0x0e, 0xce, 0xce, 0x38, 0x8b, 0x31, 0xdd, 0x0a,
	0x6d, 0x67, 0xf0, 0x04, 0x51, 0x51, 0xe9, 0xd9, 0x2a, 0xb8, 0x7a, 0xe3, 0xb3, 0x75, 0xe0, 0x7b,
	0x6e, 0x76, 0xe8, 0xcf, 0x2a, 0xdc, 0x1d, 0xf9, 0x9c, 0x45, 0x31, 0x65, 0xeb, 0xe0, 0x92, 0xcd,
	0x86, 0x03, 0x27, 0x0f, 0x89, 0x7c, 0x03, 0x55, 0xc7, 0x8d, 0x45, 0x95, 0xc4, 0xc1, 0xed, 0xde,
	0x43, 0xf3, 0xb3, 0xb6, 0x66, 0xaa, 0x1d, 0xa3, 0x39, 0x95, 0x6e, 0xc6, 0x17, 0xd0, 0x2c, 0xe2,
	0x64, 0x1f, 0x34, 0x7a, 0xf2, 0x66, 0xf2, 0xf6, 0xc4, 0x1e, 0x1c, 0xd3, 0x61, 0x47, 0x11, 0xc0,
	0x68, 0x3c, 0x3b, 0xa1, 0xf3, 0x14, 0x50, 0x8d, 0x5f, 0xf6, 0xa0, 0xd5, 0x9f, 0x0f, 0xa6, 0xc9,
	0x22, 0x0b, 0x42, 0x87, 0xda, 0x7b, 0x76, 0x1d, 0x3a, 0xf1, 0x4a, 0x57, 0x0f, 0x4b, 0x8f, 0x5a,
	0x34, 0x53, 0xc9, 0x63, 0xd0, 0xb8, 0x1b, 0x79, 0x61, 0x6c, 0xc7, 0xd7, 0x61, 0xda, 0x96, 0xed,
	0x5e, 0xdb, 0xec, 0xcf, 0x07, 0x33, 0x84, 0xe7, 0xd7, 0x21, 0xa3, 0xc0, 0x73, 0x99, 0xdc, 0x17,
	0x7d, 0xed, 0xa5, 0x77, 0xde, 0xee, 0xd5, 0x85, 0xe5, 0x20, 0xf0, 0x7c, 0x8a, 0x28, 0x79, 0x01,
	0x5a, 0x90, 0xc4, 0x61, 0x22, 0xb7, 0x2b, 0xa3, 0xd1, 0x5d, 0x73, 0x2b, 0x1a, 0x73, 0x82, 0x16,
	0xe9, 0xce, 0x41, 0x2e, 0x8b, 0x20, 0x97, 0x1e, 0x0f, 0x2f, 0x9c, 0x6b, 0xbd, 0x82, 0xed, 0x96,
	0xa9, 0xc6, 0x31, 0xc0, 0xc6, 0x87, 0xd4, 0xa1, 0x3c, 0x9f, 0x9e, 0xf6, 0x3b, 0x8a, 0x90, 0xbe,
	0x15, 0x92, 0x2a, 0xa4, 0xef, 0x84, 0xb4, 0x27, 0xa4, 0xef, 0x85, 0x54, 0x22, 0x1a, 0xd4, 0x8e,
	0x87, 0x43, 0x7a, 0x32, 0x9b, 0x75, 0xca, 0xc6, 0x03, 0xd0, 0x30, 0x02, 0xd9, 0xf2, 0x1d, 0x28,
	0x85, 0xc9, 0x42, 0x76, 0x95, 0x10, 0x8d, 0xbf, 0x54, 0x20, 0x22, 0x6b, 0xef, 0xdc, 0x1f, 0xf9,
	0x5e, 0xbc, 0x69, 0x9d, 0x34, 0x5d, 0x75, 0x67, 0xba, 0xff, 0xb8, 0x7a, 0xff, 0x81, 0xd6, 0xc2,
	0x0b, 0x9f, 0x3c, 0xb1, 0x1d, 0xd7, 0x0d, 0x12, 0x3f, 0xc6, 0x32, 0xb6, 0x68, 0x13, 0xc1, 0xe3,
	0x14, 0x2b, 0x4e, 0x56, 0x19, 0x97, 0x33, 0x95, 0xfc, 0x0b, 0xc0, 0x4f, 0xd6, 0xb6, 0xe7, 0x87,
	0x49, 0xcc, 0xb1, 0x4a, 0x2d, 0xda, 0xf0, 0x93, 0xf5, 0x08, 0x01, 0xf2, 0x00, 0x34, 0xb1, 0x9c,
	0xd6, 0x94, 0xeb, 0x55, 0x5c, 0x17, 0x1e, 0x69, 0xf5, 0x38, 0x4e, 0x54, 0xe0, 0xbe, 0x17, 0x7d,
	0xad, 0xd7, 0x70, 0x35, 0xd7, 0x8d, 0x3f, 0x54, 0x38, 0x90, 0x05, 0x18, 0xb3, 0x0f, 0x71, 0x5e,
	0xaa, 0xff, 0x43, 0x19, 0x93, 0x53, 0x37, 0x77, 0xf9, 0xa9, 0x8d, 0x89, 0x79, 0xa2, 0x19, 0xe9,
	0x42, 0xc5, 0xf3, 0x97, 0xec, 0x03, 0x16, 0xa3, 0x45, 0x53, 0x45, 0xe4, 0xbd, 0x72, 0xb8, 0xcd,
	0xbd, 0x73, 0xdf, 0x89, 0x93, 0x88, 0x61, 0xde, 0x75, 0xda, 0x5c, 0x39, 0x7c, 0x96, 0x61, 0x62,
	0x4c, 0x37, 0x06, 0x65, 0x7c, 0xe4, 0x36, 0x80, 0xf1, 0x10, 0xca, 0x58, 0xc2, 0x06, 0x54, 0x46,
	0xe3, 0xe9, 0xe9, 0xbc, 0xa3, 0x10, 0x80, 0xea, 0xe4, 0x74, 0x2e, 0x64, 0xec, 0x80, 0xe1, 0x64,
	0x7c, 0xd2, 0xd9, 0x33, 0x7e, 0xdf, 0x24, 0x82, 0x75, 0xc9, 0xae, 0xf2, 0x10, 0xb4, 0x30, 0x62,
	0x97, 0x93, 0x24, 0xb6, 0x1c, 0xbe, 0x92, 0xaf, 0x68, 0x11, 0x22, 0x06, 0x34, 0xa5, 0x3a, 0x2a,
	0xa4, 0xb0, 0x85, 0x15, 0x6c, 0xde, 0x3a, 0x17, 0x49, 0x9a, 0x48, 0x99, 0x6e, 0x61, 0xa2, 0xcc,
	0x5c, 0x1c, 0xea, 0xbb, 0x4c, 0xde, 0x60, 0xae, 0x17, 0x47, 0xb1, 0xba, 0x35, 0x8a, 0xc6, 0xaf,
	0x2a, 0x74, 0x65, 0xdc, 0xe9, 0x7d, 0x15, 0xde, 0xcd, 0x20, 0x89, 0x38, 0x46, 0x5c, 0xa7, 0x28,
	0x13, 0x43, 0xde, 0x4a, 0xa1, 0xe5, 0x0a, 0x63, 0x95, 0x5f, 0xc5, 0x65, 0x21, 0xc6, 0x54, 0x11,
	0xbb, 0xad, 0x44, 0xfe, 0x69, 0x81, 0x51, 0x2e, 0x06, 0x55, 0xd9, 0x0e, 0xea, 0xcf, 0x0a, 0xd4,
	0xb2, 0x38, 0xbe, 0x86, 0x56, 0x84, 0x4c, 0x63, 0x17, 0x88, 0x48, 0xeb, 0x75, 0xcd, 0x1d, 0xfc,
	0x63, 0x29, 0xb4, 0x19, 0x15, 0x60, 0xf2, 0x1c, 0xb4, 0x25, 0xbe, 0xf2, 0x36, 0x72, 0xc0, 0x1e,
	0xba, 0xde, 0x36, 0x77, 0x11, 0x85, 0xa5, 0x50, 0x58, 0xe6, 0x20, 0x19, 0xc2, 0xbe, 0xf4, 0xcc,
	0xd9, 0xa0, 0x84, 0xde, 0x77, 0xcd, 0xcf, 0x51, 0x87, 0xa5, 0xd0, 0xf6, 0x72, 0x6b, 0x81, 0x3c,
	0xcd, 0xcf, 0xf7, 0xfc, 0xb3, 0x00, 0xb3, 0xd7, 0x7a, 0xc4, 0xbc, 0xc1, 0x91, 0x9b, 0xc3, 0x05,
	0x48, 0x9e, 0x43, 0x93, 0xb3, 0xd8, 0x0e, 0x25, 0xd1, 0xe0, 0xcc, 0x69, 0xbd, 0x03, 0xf3, 0x26,
	0xf9, 0x58, 0x0a, 0xd5, 0xf8, 0x06, 0x15, 0xd5, 0x72, 0x91, 0x8b, 0xec, 0x05, 0x92, 0x11, 0x8e,
	0xa3, 0xa8, 0xd6, 0x0e, 0x86, 0x12, 0xd5, 0x72, 0x0b, 0xb0, 0x70, 0xe6, 0xab, 0xe0, 0xca, 0x5e,
	0x4b, 0xae, 0xc1, 0x69, 0x15, 0xce, 0x3b, 0x08, 0x48, 0x38, 0xf3, 0x02, 0x4c, 0xfe, 0x07, 0xb5,
	0x45, 0xec, 0xda, 0xe2, 0x81, 0xab, 0xa3, 0x5b, 0x7b, 0xfb, 0x01, 0xb6, 0x14, 0x5a, 0x5d, 0xc4,
	0xee, 0x34, 0x59, 0x90, 0xaf, 0xa0, 0x25, 0x4c, 0xc5, 0x94, 0xd9, 0x82, 0xdc, 0xf5, 0x86, 0xcc,
	0xef, 0xe6, 0x53, 0x28, 0xf2, 0x5b, 0xc4, 0x6e, 0x86, 0x92, 0x97, 0xd0, 0x2e, 0xb8, 0x86, 0x49,
	0xac, 0x83, 0x8c, 0x71, 0xc7, 0xf0, 0x89, 0x18, 0x73, 0xe7, 0x30, 0x11, 0xb4, 0xb8, 0x9f, 0x7b,
	0xa7, 0xef, 0x95, 0xae, 0xc9, 0x96, 0xd8, 0x35, 0x03, 0x96, 0x42, 0x5b, 0xd2, 0x3f, 0xc5, 0xc9,
	0x18, 0xba, 0x1e, 0x12, 0xa9, 0x1d, 0x21, 0x93, 0xda, 0x7c, 0xe9, 0x3a, 0xd1, 0x52, 0x6f, 0xe2,
	0x2e, 0xf7, 0x3e, 0xcf, 0xb2, 0x96, 0x42, 0x89, 0x57, 0x5c, 0x44, 0xbf, 0x7e, 0x03, 0x6a, 0x91,
	0x24, 0xf4, 0xdf, 0xf6, 0xa0, 0x9e, 0x3f, 0x7f, 0xff, 0x85, 0x1a, 0x4f, 0x7f, 0x66, 0xb2, 0xdd,
	0xeb, 0xa6, 0xfc, 0xa9, 0x59, 0x0a, 0xcd, 0x96, 0xc8, 0xbf, 0xa1, 0xc2, 0xc4, 0xb7, 0x4f, 0xf6,
	0x75, 0xd5, 0xc4, 0x4f, 0xa0, 0xa5, 0xd0, 0x14, 0x26, 0x2f, 0x3f, 0x1d, 0x9d, 0x92, 0x4c, 0x76,
	0xd7, 0x57, 0xef, 0xc6, 0xec, 0x3c, 0xdb, 0xd5, 0xbb, 0x07, 0xe6, 0xcd, 0xaf, 0xdc, 0x27, 0xcd,
	0x7b, 0x98, 0xb2, 0x5c, 0xda, 0xb3, 0x4d, 0xb3, 0x40, 0x80, 0x96, 0x82, 0xac, 0x47, 0x5e, 0x14,
	0xee, 0xdf, 0x67, 0x1f, 0xe2, 0xbc, 0x49, 0x77, 0xbc, 0xf2, 0x85, 0x06, 0x10, 0x70, 0x1f, 0xa0,
	0x1e, 0xc9, 0xa5, 0xa3, 0xc7, 0x50, 0x93, 0xcc, 0x48, 0x6a, 0x50, 0xea, 0xcf, 0x07, 0x29, 0x3b,
	0xcf, 0x85, 0xa4, 0x0a, 0xe8, 0xf5, 0x7c, 0x90, 0x92, 0xf3, 0x5c, 0x48, 0xa5, 0xa3, 0x1f, 0xf1,
	0x8b, 0xb2, 0x61, 0x49, 0x42, 0xa0, 0x3d, 0x1b, 0xd0, 0xd1, 0x74, 0x6e, 0x9f, 0x8e, 0x5f, 0x8d,
	0x27, 0xef, 0xc6, 0x1d, 0x85, 0x74, 0xa0, 0x29, 0xb1, 0x69, 0x6f, 0xfa, 0xca, 0xea, 0xa8, 0xe4,
	0x0e, 0x90, 0x1c, 0x79, 0x37, 0x7d, 0x65, 0xd9, 0xd3, 0xde, 0xcc, 0xea, 0xec, 0x91, 0x5b, 0xd0,
	0xda, 0xc2, 0x3b, 0xa5, 0x23, 0x0b, 0x4f, 0x28, 0xfc, 0x1b, 0x34, 0xa8, 0x6d, 0xb6, 0x6e, 0x40,
	0x25, 0xdb, 0xb3, 0x0e, 0x65, 0xb9, 0x0b, 0x40, 0x35, 0x73, 0x4f, 0x0d, 0xde, 0xcd, 0xac, 0x4e,
	0x79, 0x51, 0xc5, 0xaf, 0xfd, 0x97, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xd4, 0x89, 0xe1, 0x44,
	0xf0, 0x0b, 0x00, 0x00,
}
