version: "2"
run:
  concurrency: 4
  go: "1.24"
  modules-download-mode: vendor
  issues-exit-code: 1
  tests: true
linters:
  default: all
  disable:
    - bodyclose
    - cyclop
    - depguard
    - dogsled
    - dupl
    - err113
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - godot
    - godox
    - gomoddirectives
    - gosec
    - gosmopolitan
    - inamedparam
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - maintidx
    - makezero
    - mnd
    - musttag
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - protogetter
    - noinlineerr
    - testifylint
    - recvcheck
    - tagliatelle
    - varnamelen
    - whitespace
    - wrapcheck
    - modernize
    - funcorder
    - embeddedstructfieldcheck
    - wsl
    - wsl_v5
  settings:
    dupl:
      threshold: 150
    goconst:
      min-len: 3
      min-occurrences: 3
    staticcheck:
      checks:
        - all
        - -QF1008
        - -QF1009
        - -ST1003
        - -ST1000
        - -ST1005
    gocritic:
      enabled-checks:
        - builtinShadow
        - nilValReturn
        - rangeValCopy
        - typeUnparen
    lll:
      line-length: 120
    misspell:
      locale: US
    revive:
      rules:
        - name: exported
          disabled: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - gocritic
        text: 'singleCaseSwitch: should rewrite switch statement to if statement'
      - linters:
          - gocritic
        text: 'badCond: `ours == from && ours == to` condition is suspicious'
      - linters:
          - gocritic
        text: 'builtinShadow: shadowing of predeclared identifier: max'
      - linters:
          - canonicalheader
        text: 'non-canonical header "X-API-KEY", instead use: "X-Api-Key"'
      - linters:
          - testifylint
        text: 'go-require: require must only be used in the goroutine running the test function'
      - linters:
          - testifylint
        text: 'go-require: do not use require in http handlers'
      - path: _test\.go
        text: float-compare
      - linters:
          - errcheck
          - godot
          - gosec
          - testpackage
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
