include ../../../hardening.mk.inc
include ../../../env.mk.inc
CGO=1
BUILDMODE=c-shared
GOARCH=amd64
GOOS=darwin
GOTOOLCHAIN=local

darwin:
	CGO_CFLAGS="-g ${GODARWINSECFLAGS} ${CFLAGS}" \
	CGO_LDFLAGS="${GODARWINLDFLAGS} ${LFLAGS}" \
	MACOSX_DEPLOYMENT_TARGET=${MACOS_MIN_VERSION} \
	GOARCH=${GOARCH} CGO_ENABLED=${CGO} GOOS=${GOOS} GOTOOLCHAIN=${GOTOOLCHAIN} \
	go build -ldflags='-s' -x -mod=vendor \
	-buildmode="c-shared" -o ${LIBNAME}.so

clean:
	-rm -f ${LIBNAME}.so
	-rm -f ${LIBNAME}.h
