include ../../../hardening.mk.inc
include ../../../env.mk.inc
CGO=1
BUILDMODE=c-shared
GOARCH=amd64
GOOS=windows

windows:
	CGO_CFLAGS="${GOWINSECFLAGS} ${CFLAGS}" \
	CGO_LDFLAGS="${GOWINLDFLAGS} ${LFLAGS}" \
	GOARCH=${GOARCH} CGO_ENABLED=${CGO} GOOS=${GOOS} \
       	go build -x -mod=vendor \
        -buildmode="${BUILDMODE}" -o ${LIBNAME}.dll

clean:
	-rm ${LIBNAME}.dll
	-rm ${LIBNAME}.h
