package ch.shiftcrypto.bitboxapp;

import android.content.Context;
import android.content.SharedPreferences;
import android.security.keystore.KeyGenParameterSpec;
import android.security.keystore.KeyProperties;
import android.util.Base64;

import java.security.KeyStore;

import javax.crypto.Cipher;
import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;
import javax.crypto.spec.GCMParameterSpec;

/**
 * Persists the backend-generated Lightning mnemonic encryption key on Android.
 *
 * <p>The backend encrypts the Lightning mnemonic with a random 32-byte key and passes that key to
 * this helper as a Base64 string. This helper does not handle the mnemonic itself. It wraps only
 * that mnemonic encryption key with a per-account AES-GCM key stored in the Android Keystore, then
 * stores the wrapped key in SharedPreferences under an account-specific alias.</p>
 */
public class LightningEncryptionHelper {
    public static final String ERR_KEY_MISSING = "lightning-key-missing";

    private static final String PREFS_NAME = "lightning-encryption";
    private static final String KEYSTORE_PROVIDER = "AndroidKeyStore";
    private static final int GCM_TAG_LENGTH_BITS = 128;
    private static final int GCM_IV_LENGTH_BYTES = 12;

    private static String getKeyAlias(String accountCode) {
        return "bitboxapp.lightning.seed." + accountCode + ".v1";
    }

    private static SharedPreferences preferences(Context context) {
        return context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE);
    }

    private static KeyStore getKeyStore() throws Exception {
        KeyStore keyStore = KeyStore.getInstance(KEYSTORE_PROVIDER);
        keyStore.load(null);
        return keyStore;
    }

    private static SecretKey getWrappingKey(String accountCode) throws Exception {
        String alias = getKeyAlias(accountCode);
        KeyStore keyStore = getKeyStore();
        if (!keyStore.containsAlias(alias)) {
            throw new Exception(ERR_KEY_MISSING);
        }
        KeyStore.SecretKeyEntry entry = (KeyStore.SecretKeyEntry) keyStore.getEntry(alias, null);
        return entry.getSecretKey();
    }

    private static SecretKey createWrappingKey(String accountCode) throws Exception {
        String alias = getKeyAlias(accountCode);
        KeyGenerator keyGenerator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, KEYSTORE_PROVIDER);
        keyGenerator.init(new KeyGenParameterSpec.Builder(
            alias,
            KeyProperties.PURPOSE_ENCRYPT | KeyProperties.PURPOSE_DECRYPT
        )
            .setKeySize(256)
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .build());
        return keyGenerator.generateKey();
    }

    private static SecretKey getOrCreateWrappingKey(String accountCode) throws Exception {
        KeyStore keyStore = getKeyStore();
        String alias = getKeyAlias(accountCode);
        if (keyStore.containsAlias(alias)) {
            return getWrappingKey(accountCode);
        }
        return createWrappingKey(accountCode);
    }

    /**
     * Stores the Base64-encoded Lightning mnemonic encryption key for {@code accountCode}.
     *
     * <p>The value in {@code encryptionKey} is generated by the Go backend and encrypts the
     * Lightning mnemonic stored in the app config. This method creates or reuses the Android
     * Keystore wrapping key for the account, encrypts {@code encryptionKey}, and persists the
     * wrapped result in SharedPreferences.</p>
     */
    public static void storeKey(Context context, String accountCode, String encryptionKey) throws Exception {
        SecretKey wrappingKey = getOrCreateWrappingKey(accountCode);
        Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
        cipher.init(Cipher.ENCRYPT_MODE, wrappingKey);

        byte[] plaintextKey = Base64.decode(encryptionKey, Base64.DEFAULT);
        byte[] ciphertext = cipher.doFinal(plaintextKey);
        byte[] iv = cipher.getIV();
        if (iv.length != GCM_IV_LENGTH_BYTES) {
            throw new Exception("unexpected GCM IV length");
        }
        byte[] wrappedKey = new byte[iv.length + ciphertext.length];
        System.arraycopy(iv, 0, wrappedKey, 0, iv.length);
        System.arraycopy(ciphertext, 0, wrappedKey, iv.length, ciphertext.length);

        boolean success = preferences(context).edit()
            .putString(getKeyAlias(accountCode), Base64.encodeToString(wrappedKey, Base64.NO_WRAP))
            .commit();
        if (!success) {
            throw new Exception("failed to persist lightning encryption key");
        }
    }

    /**
     * Loads and unwraps the Base64-encoded Lightning mnemonic encryption key for {@code accountCode}.
     *
     * <p>The returned key is passed back to the Go backend so it can decrypt the Lightning mnemonic.
     * Throws {@link #ERR_KEY_MISSING} when either the SharedPreferences entry or the Android Keystore
     * wrapping key is missing.</p>
     */
    public static String loadKey(Context context, String accountCode) throws Exception {
        String wrappedKeyBase64 = preferences(context).getString(getKeyAlias(accountCode), null);
        if (wrappedKeyBase64 == null) {
            throw new Exception(ERR_KEY_MISSING);
        }

        SecretKey wrappingKey = getWrappingKey(accountCode);
        byte[] wrappedKey = Base64.decode(wrappedKeyBase64, Base64.DEFAULT);
        if (wrappedKey.length < GCM_IV_LENGTH_BYTES) {
            throw new Exception("wrapped key too short");
        }
        Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
        byte[] iv = new byte[GCM_IV_LENGTH_BYTES];
        System.arraycopy(wrappedKey, 0, iv, 0, iv.length);
        byte[] ciphertext = new byte[wrappedKey.length - iv.length];
        System.arraycopy(wrappedKey, iv.length, ciphertext, 0, ciphertext.length);
        cipher.init(Cipher.DECRYPT_MODE, wrappingKey, new GCMParameterSpec(GCM_TAG_LENGTH_BITS, iv));
        byte[] plaintextKey = cipher.doFinal(ciphertext);
        return Base64.encodeToString(plaintextKey, Base64.NO_WRAP);
    }

    /**
     * Deletes all Android-side key material for {@code accountCode}.
     *
     * <p>This removes both the wrapped Lightning mnemonic encryption key from SharedPreferences and
     * the account-specific Android Keystore wrapping key.</p>
     */
    public static void deleteKey(Context context, String accountCode) throws Exception {
        boolean success = preferences(context).edit()
            .remove(getKeyAlias(accountCode))
            .commit();
        if (!success) {
            throw new Exception("failed to delete lightning encryption key");
        }
        KeyStore keyStore = KeyStore.getInstance(KEYSTORE_PROVIDER);
        keyStore.load(null);
        if (keyStore.containsAlias(getKeyAlias(accountCode))) {
            keyStore.deleteEntry(getKeyAlias(accountCode));
        }
    }
}
