// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/BitBoxSwiss/bitbox-wallet-app/backend/accounts"
	"github.com/BitBoxSwiss/bitbox-wallet-app/backend/coins/eth"
	ethcommon "github.com/ethereum/go-ethereum/common"
	"math/big"
	"sync"
)

// Ensure, that TokenTransactionsFetcherMock does implement eth.TokenTransactionsFetcher.
// If this is not the case, regenerate this file with moq.
var _ eth.TokenTransactionsFetcher = &TokenTransactionsFetcherMock{}

// TokenTransactionsFetcherMock is a mock implementation of eth.TokenTransactionsFetcher.
//
//	func TestSomethingThatUsesTokenTransactionsFetcher(t *testing.T) {
//
//		// make and configure a mocked eth.TokenTransactionsFetcher
//		mockedTokenTransactionsFetcher := &TokenTransactionsFetcherMock{
//			BalancesFunc: func(ctx context.Context, addresses []ethcommon.Address) (map[ethcommon.Address]*big.Int, error) {
//				panic("mock out the Balances method")
//			},
//			BlockNumberFunc: func(ctx context.Context) (*big.Int, error) {
//				panic("mock out the BlockNumber method")
//			},
//			TokenTransactionsByContractFunc: func(ctx context.Context, blockTipHeight *big.Int, address ethcommon.Address, startBlock *big.Int, endBlock *big.Int) (map[ethcommon.Address][]*accounts.TransactionData, *big.Int, error) {
//				panic("mock out the TokenTransactionsByContract method")
//			},
//		}
//
//		// use mockedTokenTransactionsFetcher in code that requires eth.TokenTransactionsFetcher
//		// and then make assertions.
//
//	}
type TokenTransactionsFetcherMock struct {
	// BalancesFunc mocks the Balances method.
	BalancesFunc func(ctx context.Context, addresses []ethcommon.Address) (map[ethcommon.Address]*big.Int, error)

	// BlockNumberFunc mocks the BlockNumber method.
	BlockNumberFunc func(ctx context.Context) (*big.Int, error)

	// TokenTransactionsByContractFunc mocks the TokenTransactionsByContract method.
	TokenTransactionsByContractFunc func(ctx context.Context, blockTipHeight *big.Int, address ethcommon.Address, startBlock *big.Int, endBlock *big.Int) (map[ethcommon.Address][]*accounts.TransactionData, *big.Int, error)

	// calls tracks calls to the methods.
	calls struct {
		// Balances holds details about calls to the Balances method.
		Balances []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Addresses is the addresses argument value.
			Addresses []ethcommon.Address
		}
		// BlockNumber holds details about calls to the BlockNumber method.
		BlockNumber []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// TokenTransactionsByContract holds details about calls to the TokenTransactionsByContract method.
		TokenTransactionsByContract []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BlockTipHeight is the blockTipHeight argument value.
			BlockTipHeight *big.Int
			// Address is the address argument value.
			Address ethcommon.Address
			// StartBlock is the startBlock argument value.
			StartBlock *big.Int
			// EndBlock is the endBlock argument value.
			EndBlock *big.Int
		}
	}
	lockBalances                    sync.RWMutex
	lockBlockNumber                 sync.RWMutex
	lockTokenTransactionsByContract sync.RWMutex
}

// Balances calls BalancesFunc.
func (mock *TokenTransactionsFetcherMock) Balances(ctx context.Context, addresses []ethcommon.Address) (map[ethcommon.Address]*big.Int, error) {
	if mock.BalancesFunc == nil {
		panic("TokenTransactionsFetcherMock.BalancesFunc: method is nil but TokenTransactionsFetcher.Balances was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Addresses []ethcommon.Address
	}{
		Ctx:       ctx,
		Addresses: addresses,
	}
	mock.lockBalances.Lock()
	mock.calls.Balances = append(mock.calls.Balances, callInfo)
	mock.lockBalances.Unlock()
	return mock.BalancesFunc(ctx, addresses)
}

// BalancesCalls gets all the calls that were made to Balances.
// Check the length with:
//
//	len(mockedTokenTransactionsFetcher.BalancesCalls())
func (mock *TokenTransactionsFetcherMock) BalancesCalls() []struct {
	Ctx       context.Context
	Addresses []ethcommon.Address
} {
	var calls []struct {
		Ctx       context.Context
		Addresses []ethcommon.Address
	}
	mock.lockBalances.RLock()
	calls = mock.calls.Balances
	mock.lockBalances.RUnlock()
	return calls
}

// BlockNumber calls BlockNumberFunc.
func (mock *TokenTransactionsFetcherMock) BlockNumber(ctx context.Context) (*big.Int, error) {
	if mock.BlockNumberFunc == nil {
		panic("TokenTransactionsFetcherMock.BlockNumberFunc: method is nil but TokenTransactionsFetcher.BlockNumber was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockBlockNumber.Lock()
	mock.calls.BlockNumber = append(mock.calls.BlockNumber, callInfo)
	mock.lockBlockNumber.Unlock()
	return mock.BlockNumberFunc(ctx)
}

// BlockNumberCalls gets all the calls that were made to BlockNumber.
// Check the length with:
//
//	len(mockedTokenTransactionsFetcher.BlockNumberCalls())
func (mock *TokenTransactionsFetcherMock) BlockNumberCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockBlockNumber.RLock()
	calls = mock.calls.BlockNumber
	mock.lockBlockNumber.RUnlock()
	return calls
}

// TokenTransactionsByContract calls TokenTransactionsByContractFunc.
func (mock *TokenTransactionsFetcherMock) TokenTransactionsByContract(ctx context.Context, blockTipHeight *big.Int, address ethcommon.Address, startBlock *big.Int, endBlock *big.Int) (map[ethcommon.Address][]*accounts.TransactionData, *big.Int, error) {
	if mock.TokenTransactionsByContractFunc == nil {
		panic("TokenTransactionsFetcherMock.TokenTransactionsByContractFunc: method is nil but TokenTransactionsFetcher.TokenTransactionsByContract was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		BlockTipHeight *big.Int
		Address        ethcommon.Address
		StartBlock     *big.Int
		EndBlock       *big.Int
	}{
		Ctx:            ctx,
		BlockTipHeight: blockTipHeight,
		Address:        address,
		StartBlock:     startBlock,
		EndBlock:       endBlock,
	}
	mock.lockTokenTransactionsByContract.Lock()
	mock.calls.TokenTransactionsByContract = append(mock.calls.TokenTransactionsByContract, callInfo)
	mock.lockTokenTransactionsByContract.Unlock()
	return mock.TokenTransactionsByContractFunc(ctx, blockTipHeight, address, startBlock, endBlock)
}

// TokenTransactionsByContractCalls gets all the calls that were made to TokenTransactionsByContract.
// Check the length with:
//
//	len(mockedTokenTransactionsFetcher.TokenTransactionsByContractCalls())
func (mock *TokenTransactionsFetcherMock) TokenTransactionsByContractCalls() []struct {
	Ctx            context.Context
	BlockTipHeight *big.Int
	Address        ethcommon.Address
	StartBlock     *big.Int
	EndBlock       *big.Int
} {
	var calls []struct {
		Ctx            context.Context
		BlockTipHeight *big.Int
		Address        ethcommon.Address
		StartBlock     *big.Int
		EndBlock       *big.Int
	}
	mock.lockTokenTransactionsByContract.RLock()
	calls = mock.calls.TokenTransactionsByContract
	mock.lockTokenTransactionsByContract.RUnlock()
	return calls
}
