// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	headers "github.com/BitBoxSwiss/bitbox-wallet-app/backend/coins/btc/headers"
	mock "github.com/stretchr/testify/mock"

	wire "github.com/btcsuite/btcd/wire"
)

// Interface is an autogenerated mock type for the Interface type
type Interface struct {
	mock.Mock
}

// HeaderByHeight provides a mock function with given fields: _a0
func (_m *Interface) HeaderByHeight(_a0 int) (*wire.BlockHeader, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for HeaderByHeight")
	}

	var r0 *wire.BlockHeader
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*wire.BlockHeader, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(int) *wire.BlockHeader); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wire.BlockHeader)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Initialize provides a mock function with no fields
func (_m *Interface) Initialize() {
	_m.Called()
}

// Status provides a mock function with no fields
func (_m *Interface) Status() (*headers.Status, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 *headers.Status
	var r1 error
	if rf, ok := ret.Get(0).(func() (*headers.Status, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *headers.Status); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*headers.Status)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubscribeEvent provides a mock function with given fields: f
func (_m *Interface) SubscribeEvent(f func(headers.Event)) func() {
	ret := _m.Called(f)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeEvent")
	}

	var r0 func()
	if rf, ok := ret.Get(0).(func(func(headers.Event)) func()); ok {
		r0 = rf(f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func())
		}
	}

	return r0
}

// TipHeight provides a mock function with no fields
func (_m *Interface) TipHeight() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TipHeight")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// VerifiedHeaderByHeight provides a mock function with given fields: _a0
func (_m *Interface) VerifiedHeaderByHeight(_a0 int) (*wire.BlockHeader, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for VerifiedHeaderByHeight")
	}

	var r0 *wire.BlockHeader
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*wire.BlockHeader, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(int) *wire.BlockHeader); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wire.BlockHeader)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewInterface creates a new instance of Interface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *Interface {
	mock := &Interface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
