# SPDX-License-Identifier: Apache-2.0

dev:
	npm start
lint:
	npm run lint
fix:
	npm run lint -- --fix
jstest:
	npm test
jstest-watch:
	npm test -- --watch
jstest-cover:
	npm test -- --coverage
listdeps:
	@echo "Listing JavaScript production dependencies. Be careful to not pull in many deps accidentally."
	npm list -prod -long
serve:
	npm run serve
test-e2e:
	npm run test-e2e
