# Copyright 2018 Shift Devices AG
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

dev:
	yarn run dev
lint:
	yarn run lint
jstest:
	yarn run test
jstest-watch:
	yarn run test --watch
jstest-cover:
	yarn run test --coverage
listdeps:
	@echo "Listing javascript production dependencies. Be careful to not pull in many deps accidentally."
	NODE_ENV=production yarn list
